"""Worldline — materialized query artifacts for propstore.

A worldline is a specific traced path through the knowledge space,
determined by inputs (bindings + overrides), a resolution policy,
and a set of target concepts. It captures the question (inputs + policy +
targets) and optionally the answer (results + dependencies + derivation trace).

Grounded in: de Kleer 1986 (ATMS labels), Martins 1983 (belief spaces),
Green 2007 (provenance semirings), Groth 2010 (nanopublications).
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from propstore.world.types import Environment, RenderPolicy


@dataclass
class WorldlineInputs:
    """The input specification for a worldline query."""

    environment: Environment = field(default_factory=Environment)
    overrides: dict[str, float | str] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict | None) -> WorldlineInputs:
        if not data:
            return cls()
        return cls(
            environment=Environment.from_dict(data),
            overrides=dict(data.get("overrides") or {}),
        )

    def to_dict(self) -> dict:
        d = self.environment.to_dict()
        if self.overrides:
            d["overrides"] = dict(self.overrides)
        return d

@dataclass
class WorldlineResult:
    """The materialized results of a worldline query."""

    computed: str = ""
    content_hash: str = ""
    values: dict[str, dict[str, Any]] = field(default_factory=dict)
    steps: list[dict[str, Any]] = field(default_factory=list)
    dependencies: dict[str, list[str]] = field(default_factory=lambda: {
        "claims": [], "stances": [], "contexts": [],
    })
    sensitivity: dict[str, Any] | None = None
    argumentation: dict[str, Any] | None = None

    @classmethod
    def from_dict(cls, data: dict | None) -> WorldlineResult | None:
        if not data:
            return None
        return cls(
            computed=data.get("computed", ""),
            content_hash=data.get("content_hash", ""),
            values=dict(data.get("values") or {}),
            steps=list(data.get("steps") or []),
            dependencies=data.get("dependencies") or {"claims": [], "stances": [], "contexts": []},
            sensitivity=data.get("sensitivity"),
            argumentation=data.get("argumentation"),
        )

    def to_dict(self) -> dict:
        d: dict[str, Any] = {
            "computed": self.computed,
            "content_hash": self.content_hash,
            "values": self.values,
            "steps": self.steps,
            "dependencies": self.dependencies,
        }
        if self.sensitivity is not None:
            d["sensitivity"] = self.sensitivity
        if self.argumentation is not None:
            d["argumentation"] = self.argumentation
        return d


@dataclass
class WorldlineDefinition:
    """A worldline: question + optional answer.

    The question (id, name, inputs, policy, targets) is human-authored.
    The answer (results) is machine-generated by run_worldline().
    """

    id: str
    name: str = ""
    created: str = ""
    inputs: WorldlineInputs = field(default_factory=WorldlineInputs)
    policy: RenderPolicy = field(default_factory=RenderPolicy)
    targets: list[str] = field(default_factory=list)
    results: WorldlineResult | None = None

    @classmethod
    def from_dict(cls, data: dict) -> WorldlineDefinition:
        if "id" not in data:
            raise ValueError("Worldline definition requires 'id'")
        targets = data.get("targets")
        if not targets:
            raise ValueError("Worldline definition requires 'targets'")

        results = WorldlineResult.from_dict(data.get("results"))

        return cls(
            id=data["id"],
            name=data.get("name", ""),
            created=data.get("created", ""),
            inputs=WorldlineInputs.from_dict(data.get("inputs")),
            policy=RenderPolicy.from_dict(data.get("policy")),
            targets=list(targets),
            results=results,
        )

    @classmethod
    def from_file(cls, path: Path) -> WorldlineDefinition:
        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if not isinstance(data, dict):
            raise ValueError(f"Worldline file {path} is not a YAML mapping")
        return cls.from_dict(data)

    def to_dict(self) -> dict:
        d: dict[str, Any] = {
            "id": self.id,
        }
        if self.name:
            d["name"] = self.name
        if self.created:
            d["created"] = self.created

        inputs = self.inputs.to_dict()
        if inputs:
            d["inputs"] = inputs

        policy = self.policy.to_dict()
        if policy:
            d["policy"] = policy

        d["targets"] = list(self.targets)

        if self.results is not None:
            d["results"] = self.results.to_dict()

        return d

    def to_file(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            yaml.dump(self.to_dict(), f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def is_stale(self, world) -> bool:
        """Check if this worldline's results are stale.

        A worldline is stale if re-materializing it under the current world
        produces a different fingerprint than the stored results.
        """
        if self.results is None:
            return False  # No results → not stale, just unrun

        stored_hash = self.results.content_hash
        if not stored_hash:
            return True  # No hash → assume stale

        from propstore.worldline_runner import run_worldline

        current_results = run_worldline(self, world)
        current_hash = current_results.content_hash
        return current_hash != stored_hash


def compute_worldline_content_hash(
    *,
    values: dict[str, dict[str, Any]],
    steps: list[dict[str, Any]],
    dependencies: dict[str, list[str]],
    sensitivity: dict[str, Any] | None,
    argumentation: dict[str, Any] | None,
) -> str:
    """Compute a deterministic fingerprint for materialized worldline content."""
    payload = {
        "values": values,
        "steps": steps,
        "dependencies": dependencies,
        "sensitivity": sensitivity,
        "argumentation": argumentation,
    }
    encoded = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()[:16]
