"""Tests for sensitivity analysis — Feature 6."""

import pytest
import yaml

from propstore.build_sidecar import build_sidecar
from propstore.sensitivity import SensitivityEntry, SensitivityResult, analyze_sensitivity
from propstore.validate import load_concepts
from propstore.world_model import WorldModel


# ── Fixtures ─────────────────────────────────────────────────────────


@pytest.fixture
def concept_dir(tmp_path):
    """Create a concepts directory with test concepts."""
    knowledge = tmp_path / "knowledge"
    concepts_path = knowledge / "concepts"
    concepts_path.mkdir(parents=True)
    counters = concepts_path / ".counters"
    counters.mkdir()
    (counters / "speech.next").write_text("5")

    forms_dir = knowledge / "forms"
    forms_dir.mkdir()
    for form_name in ("frequency", "category", "structural", "duration_ratio",
                      "pressure", "time"):
        (forms_dir / f"{form_name}.yaml").write_text(
            yaml.dump({"name": form_name}, default_flow_style=False))

    def write(name, data):
        (concepts_path / f"{name}.yaml").write_text(yaml.dump(data, default_flow_style=False))

    write("fundamental_frequency", {
        "id": "concept1",
        "canonical_name": "fundamental_frequency",
        "status": "accepted",
        "definition": "The rate of vocal fold vibration during phonation.",
        "domain": "speech",
        "created_date": "2026-03-15",
        "form": "frequency",
        "range": [50, 1000],
        "aliases": [
            {"name": "F0", "source": "common"},
            {"name": "pitch", "source": "common", "note": "perceptual correlate"},
        ],
        "relationships": [
            {"type": "broader", "target": "concept4"},
        ],
    })

    write("subglottal_pressure", {
        "id": "concept2",
        "canonical_name": "subglottal_pressure",
        "status": "accepted",
        "definition": "Air pressure below the glottis during phonation.",
        "domain": "speech",
        "form": "pressure",
        "aliases": [
            {"name": "Ps", "source": "Sundberg_1993"},
        ],
    })

    write("task", {
        "id": "concept3",
        "canonical_name": "task",
        "status": "accepted",
        "definition": "The vocal activity type used in an experiment.",
        "domain": "speech",
        "form": "category",
        "form_parameters": {"values": ["speech", "singing", "whisper"], "extensible": True},
    })

    write("voice_source", {
        "id": "concept4",
        "canonical_name": "voice_source",
        "status": "accepted",
        "definition": "The acoustic signal generated by the vibrating vocal folds.",
        "domain": "speech",
        "form": "structural",
        "relationships": [
            {"type": "narrower", "target": "concept1"},
            {"type": "narrower", "target": "concept2"},
        ],
    })

    write("return_phase_ratio", {
        "id": "concept5",
        "canonical_name": "return_phase_ratio",
        "status": "proposed",
        "definition": "Ratio of return phase time to fundamental period.",
        "domain": "speech",
        "form": "duration_ratio",
        "aliases": [
            {"name": "ra", "source": "Gobl_1988"},
            {"name": "Ra", "source": "Fant_1985", "note": "unnormalized"},
        ],
        "parameterization_relationships": [{
            "formula": "ra = ta * F0",
            "sympy": "Eq(concept5, concept6 * concept1)",
            "inputs": ["concept6", "concept1"],
            "exactness": "exact",
            "source": "Fant_1985",
            "bidirectional": True,
            "conditions": ["task == 'speech'"],
        }],
    })

    write("return_phase_time", {
        "id": "concept6",
        "canonical_name": "return_phase_time",
        "status": "proposed",
        "definition": "Duration of the return phase of the glottal cycle.",
        "domain": "speech",
        "form": "time",
        "aliases": [
            {"name": "ta", "source": "Fant_1985"},
        ],
    })

    write("derived_ratio", {
        "id": "concept7",
        "canonical_name": "derived_ratio",
        "status": "proposed",
        "definition": "A ratio derived from return_phase_ratio for testing chains.",
        "domain": "speech",
        "form": "duration_ratio",
        "parameterization_relationships": [{
            "formula": "dr = 2 * ra",
            "sympy": "Eq(concept7, 2 * concept5)",
            "inputs": ["concept5"],
            "exactness": "exact",
            "source": "test",
            "conditions": ["task == 'speech'"],
        }],
    })

    return concepts_path


@pytest.fixture
def repo(concept_dir):
    from propstore.cli.repository import Repository
    return Repository(concept_dir.parent)


@pytest.fixture
def claim_files(concept_dir):
    """Create claim files with known conditions for binding tests."""
    claims_dir = concept_dir / "claims_data"
    claims_dir.mkdir(exist_ok=True)

    alpha = {
        "source": {"paper": "test_paper_alpha"},
        "claims": [
            {
                "id": "claim1",
                "type": "parameter",
                "concept": "concept1",
                "value": 200.0,
                "unit": "Hz",
                "sample_size": 30,
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 5,
                               "date": "2024-01-15"},
            },
            {
                "id": "claim2",
                "type": "parameter",
                "concept": "concept1",
                "value": 350.0,
                "unit": "Hz",
                "sample_size": 10,
                "conditions": ["task == 'speech'"],
                "stances": [
                    {
                        "type": "contradicts",
                        "target": "claim1",
                        "strength": "strong",
                        "note": "same task, conflicting value",
                    }
                ],
                "provenance": {"paper": "test_paper_alpha", "page": 8,
                               "date": "2024-06-20"},
            },
            {
                "id": "claim3",
                "type": "parameter",
                "concept": "concept1",
                "value": 180.0,
                "unit": "Hz",
                "conditions": ["task == 'singing'"],
                "provenance": {"paper": "test_paper_alpha", "page": 12},
            },
            {
                "id": "claim4",
                "type": "parameter",
                "concept": "concept2",
                "value": 800.0,
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 15},
            },
            {
                "id": "claim5",
                "type": "observation",
                "statement": "F0 increases with Ps logarithmically.",
                "concepts": ["concept1", "concept2"],
                "provenance": {"paper": "test_paper_alpha", "page": 20},
            },
            {
                "id": "claim10",
                "type": "parameter",
                "concept": "concept6",
                "value": 0.001,
                "unit": "s",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 25},
            },
        ],
    }

    beta = {
        "source": {"paper": "test_paper_beta"},
        "claims": [
            {
                "id": "claim6",
                "type": "parameter",
                "concept": "concept2",
                "value": 800.0,
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 3},
            },
            {
                "id": "claim7",
                "type": "parameter",
                "concept": "concept1",
                "value": 250.0,
                "unit": "Hz",
                "sample_size": 50,
                "conditions": ["task == 'speech'", "fundamental_frequency > 100"],
                "provenance": {"paper": "test_paper_beta", "page": 7,
                               "date": "2023-03-10"},
                "stances": [
                    {
                        "type": "supports",
                        "target": "claim1",
                        "strength": "moderate",
                        "note": "confirms F0 range",
                    }
                ],
            },
            {
                "id": "claim8",
                "type": "equation",
                "expression": "log(Ps) = 1.00 + 0.88 * log(F0)",
                "sympy": "Eq(log(Ps), 1.00 + 0.88 * log(F0))",
                "variables": [
                    {"symbol": "Ps", "concept": "concept2", "role": "dependent"},
                    {"symbol": "F0", "concept": "concept1", "role": "independent"},
                ],
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 19},
            },
            {
                "id": "claim9",
                "type": "parameter",
                "concept": "concept1",
                "value": 220.0,
                "unit": "Hz",
                "conditions": ["task == 'whisper'"],
                "provenance": {"paper": "test_paper_beta", "page": 22},
            },
        ],
    }

    (claims_dir / "test_paper_alpha.yaml").write_text(yaml.dump(alpha, default_flow_style=False))
    (claims_dir / "test_paper_beta.yaml").write_text(yaml.dump(beta, default_flow_style=False))

    from propstore.validate_claims import load_claim_files
    return load_claim_files(claims_dir)


@pytest.fixture
def world(concept_dir, repo, claim_files):
    """Build sidecar and return a WorldModel."""
    concepts = load_concepts(concept_dir)
    concept_registry = {c.data["id"]: c.data for c in concepts if c.data.get("id")}
    build_sidecar(concepts, repo.sidecar_path, claim_files=claim_files,
                  concept_registry=concept_registry, repo=repo)
    return WorldModel(repo)


# ── Nonlinear fixture (separate, minimal) ────────────────────────────


@pytest.fixture
def nonlinear_world(tmp_path):
    """Minimal fixture with a nonlinear parameterization: out = a^2 * b."""
    knowledge = tmp_path / "knowledge"
    concepts_path = knowledge / "concepts"
    concepts_path.mkdir(parents=True)
    counters = concepts_path / ".counters"
    counters.mkdir()
    (counters / "speech.next").write_text("5")

    forms_dir = knowledge / "forms"
    forms_dir.mkdir()
    for form_name in ("quantity", "category"):
        (forms_dir / f"{form_name}.yaml").write_text(
            yaml.dump({"name": form_name}, default_flow_style=False))

    def write(name, data):
        (concepts_path / f"{name}.yaml").write_text(yaml.dump(data, default_flow_style=False))

    write("input_a", {
        "id": "ca",
        "canonical_name": "input_a",
        "status": "accepted",
        "definition": "Input A for nonlinear test.",
        "domain": "test",
        "form": "quantity",
    })

    write("input_b", {
        "id": "cb",
        "canonical_name": "input_b",
        "status": "accepted",
        "definition": "Input B for nonlinear test.",
        "domain": "test",
        "form": "quantity",
    })

    write("output_nl", {
        "id": "cout",
        "canonical_name": "output_nl",
        "status": "accepted",
        "definition": "Nonlinear output = a^2 * b.",
        "domain": "test",
        "form": "quantity",
        "parameterization_relationships": [{
            "formula": "out = a^2 * b",
            "sympy": "Eq(cout, ca**2 * cb)",
            "inputs": ["ca", "cb"],
            "exactness": "exact",
            "source": "test",
        }],
    })

    write("task_nl", {
        "id": "ct",
        "canonical_name": "task_nl",
        "status": "accepted",
        "definition": "Task category for nonlinear test.",
        "domain": "test",
        "form": "category",
        "form_parameters": {"values": ["run"], "extensible": True},
    })

    claims_dir = concepts_path / "claims_data"
    claims_dir.mkdir()
    claims = {
        "source": {"paper": "nl_test"},
        "claims": [
            {
                "id": "nla",
                "type": "parameter",
                "concept": "ca",
                "value": 3.0,
                "unit": "x",
                "provenance": {"paper": "nl_test", "page": 1},
            },
            {
                "id": "nlb",
                "type": "parameter",
                "concept": "cb",
                "value": 2.0,
                "unit": "x",
                "provenance": {"paper": "nl_test", "page": 1},
            },
        ],
    }
    (claims_dir / "nl_test.yaml").write_text(yaml.dump(claims, default_flow_style=False))

    from propstore.cli.repository import Repository
    from propstore.validate_claims import load_claim_files

    repo = Repository(knowledge)
    cf = load_claim_files(claims_dir)
    concepts = load_concepts(concepts_path)
    concept_registry = {c.data["id"]: c.data for c in concepts if c.data.get("id")}
    build_sidecar(concepts, repo.sidecar_path, claim_files=cf,
                  concept_registry=concept_registry, repo=repo)
    return WorldModel(repo)


# ── Tests ─────────────────────────────────────────────────────────────


class TestSensitivityLinear:
    """concept5 = concept6 * concept1 under speech, with overrides."""

    def test_sensitivity_linear(self, world):
        bound = world.bind(task="speech")
        result = analyze_sensitivity(
            world, "concept5", bound,
            override_values={"concept1": 200.0, "concept6": 0.001},
        )
        assert result is not None
        assert result.concept_id == "concept5"
        assert len(result.entries) == 2

        # Both inputs should have partial derivatives
        ids = {e.input_concept_id for e in result.entries}
        assert ids == {"concept1", "concept6"}

        # Check partial derivative values:
        #   d(concept6 * concept1)/d(concept1) = concept6 = 0.001
        #   d(concept6 * concept1)/d(concept6) = concept1 = 200.0
        for entry in result.entries:
            assert entry.partial_derivative_value is not None
            if entry.input_concept_id == "concept1":
                assert entry.partial_derivative_value == pytest.approx(0.001)
            elif entry.input_concept_id == "concept6":
                assert entry.partial_derivative_value == pytest.approx(200.0)


class TestSensitivityRanking:
    """Entries sorted by |elasticity| descending."""

    def test_sensitivity_ranking(self, world):
        bound = world.bind(task="speech")
        result = analyze_sensitivity(
            world, "concept5", bound,
            override_values={"concept1": 200.0, "concept6": 0.001},
        )
        assert result is not None
        assert len(result.entries) >= 2

        # For f = a * b, all elasticities are 1.0, so order doesn't matter
        # but they should all be present and sorted (ties are fine)
        elasticities = [abs(e.elasticity) for e in result.entries if e.elasticity is not None]
        assert elasticities == sorted(elasticities, reverse=True)


class TestSensitivityNoParameterization:
    """concept2 has no parameterization -> returns None."""

    def test_sensitivity_no_parameterization(self, world):
        bound = world.bind(task="speech")
        result = analyze_sensitivity(world, "concept2", bound)
        assert result is None


class TestSensitivityUnderspecifiedInputs:
    """Returns None when inputs can't be resolved and no overrides given."""

    def test_sensitivity_underspecified_inputs(self, world):
        # Under speech, concept1 is conflicted (claims 1,2,7 have different values)
        # and no override is given, so we can't resolve
        bound = world.bind(task="speech")
        result = analyze_sensitivity(world, "concept5", bound)
        # concept1 is conflicted -> value_of returns conflicted -> can't resolve -> None
        assert result is None


class TestSensitivityElasticityValues:
    """For f = a * b: elasticity of each input = 1.0."""

    def test_sensitivity_elasticity_values(self, world):
        bound = world.bind(task="speech")
        result = analyze_sensitivity(
            world, "concept5", bound,
            override_values={"concept1": 200.0, "concept6": 0.001},
        )
        assert result is not None

        for entry in result.entries:
            assert entry.elasticity is not None
            assert entry.elasticity == pytest.approx(1.0)


class TestSensitivityNonlinear:
    """For f = a^2 * b: elasticity of a = 2.0, elasticity of b = 1.0."""

    def test_sensitivity_nonlinear(self, nonlinear_world):
        bound = nonlinear_world.bind()
        result = analyze_sensitivity(
            nonlinear_world, "cout", bound,
            override_values={"ca": 3.0, "cb": 2.0},
        )
        assert result is not None
        assert result.output_value == pytest.approx(18.0)  # 3^2 * 2

        by_id = {e.input_concept_id: e for e in result.entries}
        assert by_id["ca"].elasticity == pytest.approx(2.0)
        assert by_id["cb"].elasticity == pytest.approx(1.0)

        # ca should be first (higher elasticity)
        assert result.entries[0].input_concept_id == "ca"


class TestSensitivityConditionsRespected:
    """Parameterization with conditions task=='speech', bind singing -> returns None."""

    def test_sensitivity_conditions_respected(self, world):
        bound = world.bind(task="singing")
        result = analyze_sensitivity(world, "concept5", bound)
        assert result is None
