"""Tests for the SQLite sidecar builder.

Verifies that the sidecar builder creates the correct tables,
populates them from concept YAML files, and builds the FTS5 index.
"""

import sqlite3

import pytest
import yaml

from compiler.build_sidecar import build_sidecar
from compiler.validate import load_concepts


@pytest.fixture
def concept_dir(tmp_path):
    """Create a concepts directory with a few test concepts."""
    counters = tmp_path / ".counters"
    counters.mkdir()
    (counters / "speech.next").write_text("5")
    (counters / "narr.next").write_text("2")

    def write(name, data):
        (tmp_path / f"{name}.yaml").write_text(yaml.dump(data, default_flow_style=False))

    write("fundamental_frequency", {
        "id": "speech_0001",
        "canonical_name": "fundamental_frequency",
        "status": "accepted",
        "definition": "The rate of vocal fold vibration during phonation.",
        "domain": "speech",
        "created_date": "2026-03-15",
        "kind": {"quantity": {"unit": "Hz", "dimension": "frequency", "range": [50, 1000]}},
        "aliases": [
            {"name": "F0", "source": "common"},
            {"name": "pitch", "source": "common", "note": "perceptual correlate"},
        ],
        "relationships": [
            {"type": "broader", "target": "speech_0004"},
        ],
    })

    write("subglottal_pressure", {
        "id": "speech_0002",
        "canonical_name": "subglottal_pressure",
        "status": "accepted",
        "definition": "Air pressure below the glottis during phonation.",
        "domain": "speech",
        "kind": {"quantity": {"unit": "Pa", "dimension": "pressure"}},
        "aliases": [
            {"name": "Ps", "source": "Sundberg_1993"},
        ],
    })

    write("task", {
        "id": "speech_0003",
        "canonical_name": "task",
        "status": "accepted",
        "definition": "The vocal activity type used in an experiment.",
        "domain": "speech",
        "kind": {"category": {"values": ["speech", "singing", "whisper"], "extensible": True}},
    })

    write("voice_source", {
        "id": "speech_0004",
        "canonical_name": "voice_source",
        "status": "accepted",
        "definition": "The acoustic signal generated by the vibrating vocal folds.",
        "domain": "speech",
        "kind": {"structural": {"note": "Parent concept"}},
        "relationships": [
            {"type": "narrower", "target": "speech_0001"},
            {"type": "narrower", "target": "speech_0002"},
        ],
    })

    write("return_phase_ratio", {
        "id": "speech_0005",
        "canonical_name": "return_phase_ratio",
        "status": "proposed",
        "definition": "Ratio of return phase time to fundamental period.",
        "domain": "speech",
        "kind": {"quantity": {"unit": "%", "dimension": "dimensionless ratio"}},
        "aliases": [
            {"name": "ra", "source": "Gobl_1988"},
            {"name": "Ra", "source": "Fant_1985", "note": "unnormalized"},
        ],
        "parameterization_relationships": [{
            "formula": "ra = ta / T0",
            "sympy": "Eq(ra, ta / T0)",
            "inputs": ["speech_0005", "speech_0001"],
            "exactness": "exact",
            "source": "Fant_1985",
            "bidirectional": True,
            "conditions": ["task == 'speech'"],
        }],
    })

    return tmp_path


@pytest.fixture
def sidecar_path(tmp_path):
    return tmp_path / "sidecar" / "propstore.sqlite"


# ── Table existence ──────────────────────────────────────────────────

class TestTableCreation:
    def test_creates_sqlite_file(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        assert sidecar_path.exists()

    def test_concept_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='concept'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_alias_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='alias'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_relationship_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='relationship'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_parameterization_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='parameterization'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_fts_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='concept_fts'")
        assert cursor.fetchone() is not None
        conn.close()


# ── Concept table contents ───────────────────────────────────────────

class TestConceptTable:
    def test_concept_count(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        count = conn.execute("SELECT COUNT(*) FROM concept").fetchone()[0]
        assert count == 5
        conn.close()

    def test_concept_fields(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM concept WHERE id='speech_0001'").fetchone()
        assert row["canonical_name"] == "fundamental_frequency"
        assert row["status"] == "accepted"
        assert row["domain"] == "speech"
        assert row["kind_type"] == "quantity"
        assert "vocal fold" in row["definition"]
        conn.close()

    def test_proposed_concept_included(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute("SELECT status FROM concept WHERE id='speech_0005'").fetchone()
        assert row[0] == "proposed"
        conn.close()


# ── Alias table contents ─────────────────────────────────────────────

class TestAliasTable:
    def test_alias_count(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        count = conn.execute("SELECT COUNT(*) FROM alias").fetchone()[0]
        # F0, pitch, Ps, ra, Ra = 5
        assert count == 5
        conn.close()

    def test_alias_lookup(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute(
            "SELECT concept_id FROM alias WHERE alias_name='F0'"
        ).fetchone()
        assert row[0] == "speech_0001"
        conn.close()

    def test_alias_source(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute(
            "SELECT source FROM alias WHERE alias_name='Ps'"
        ).fetchone()
        assert row[0] == "Sundberg_1993"
        conn.close()


# ── Relationship table contents ──────────────────────────────────────

class TestRelationshipTable:
    def test_relationship_count(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        count = conn.execute("SELECT COUNT(*) FROM relationship").fetchone()[0]
        # broader(speech_0001→speech_0004), narrower(speech_0004→speech_0001),
        # narrower(speech_0004→speech_0002) = 3
        assert count == 3
        conn.close()

    def test_relationship_fields(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT * FROM relationship WHERE source_id='speech_0001'"
        ).fetchone()
        assert row["type"] == "broader"
        assert row["target_id"] == "speech_0004"
        conn.close()


# ── Parameterization table contents ──────────────────────────────────

class TestParameterizationTable:
    def test_parameterization_count(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        count = conn.execute("SELECT COUNT(*) FROM parameterization").fetchone()[0]
        assert count == 1
        conn.close()

    def test_parameterization_fields(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM parameterization").fetchone()
        assert "speech_0005" in row["concept_ids"]
        assert row["formula"] == "ra = ta / T0"
        assert row["exactness"] == "exact"
        conn.close()


# ── FTS5 index ───────────────────────────────────────────────────────

class TestFTS:
    def test_fts_search_by_name(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        rows = conn.execute(
            "SELECT concept_id FROM concept_fts WHERE concept_fts MATCH 'frequency'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "speech_0001" in ids
        conn.close()

    def test_fts_search_by_alias(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        rows = conn.execute(
            "SELECT concept_id FROM concept_fts WHERE concept_fts MATCH 'pitch'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "speech_0001" in ids
        conn.close()

    def test_fts_search_by_definition(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        rows = conn.execute(
            "SELECT concept_id FROM concept_fts WHERE concept_fts MATCH 'glottis'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "speech_0002" in ids
        conn.close()

    def test_fts_search_by_condition(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        rows = conn.execute(
            "SELECT concept_id FROM concept_fts WHERE concept_fts MATCH 'speech'"
        ).fetchall()
        ids = [r[0] for r in rows]
        # return_phase_ratio has condition "task == 'speech'"
        assert "speech_0005" in ids
        conn.close()


# ── Rebuild skipping ─────────────────────────────────────────────────

class TestRebuildSkipping:
    def test_skip_rebuild_when_unchanged(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        mtime1 = sidecar_path.stat().st_mtime

        # Build again — should skip
        import time
        time.sleep(0.1)  # ensure different mtime if rebuilt
        build_sidecar(concepts, sidecar_path)
        mtime2 = sidecar_path.stat().st_mtime
        assert mtime1 == mtime2

    def test_rebuild_when_forced(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        mtime1 = sidecar_path.stat().st_mtime

        import time
        time.sleep(0.1)
        build_sidecar(concepts, sidecar_path, force=True)
        mtime2 = sidecar_path.stat().st_mtime
        assert mtime2 > mtime1


# ── Claim fixtures ───────────────────────────────────────────────────

@pytest.fixture
def claim_files(concept_dir):
    """Create claim files in a claims subdirectory alongside concepts."""
    claims_dir = concept_dir / "claims_data"
    claims_dir.mkdir(exist_ok=True)

    alpha = {
        "source": {"paper": "test_paper_alpha"},
        "claims": [
            {
                "id": "claim_0001",
                "type": "parameter",
                "concept": "speech_0001",
                "value": [200.0],
                "unit": "Hz",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 5},
            },
            {
                "id": "claim_0002",
                "type": "parameter",
                "concept": "speech_0001",
                "value": [350.0],
                "unit": "Hz",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 8, "table": "Table 2"},
            },
            {
                "id": "claim_0003",
                "type": "parameter",
                "concept": "speech_0001",
                "value": [180.0],
                "unit": "Hz",
                "conditions": ["task == 'singing'"],
                "provenance": {"paper": "test_paper_alpha", "page": 12},
            },
            {
                "id": "claim_0004",
                "type": "parameter",
                "concept": "speech_0002",
                "value": [800.0],
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 15},
            },
            {
                "id": "claim_0005",
                "type": "observation",
                "statement": "Fundamental frequency increases with subglottal pressure in a roughly logarithmic relationship.",
                "concepts": ["speech_0001", "speech_0002"],
                "provenance": {"paper": "test_paper_alpha", "page": 20, "section": "Discussion"},
            },
        ],
    }

    beta = {
        "source": {"paper": "test_paper_beta"},
        "claims": [
            {
                "id": "claim_0006",
                "type": "parameter",
                "concept": "speech_0002",
                "value": [800.0],
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 3},
            },
            {
                "id": "claim_0007",
                "type": "parameter",
                "concept": "speech_0001",
                "value": [250.0],
                "unit": "Hz",
                "conditions": ["task == 'speech'", "fundamental_frequency > 100"],
                "provenance": {"paper": "test_paper_beta", "page": 7},
            },
            {
                "id": "claim_0008",
                "type": "equation",
                "expression": "log(Ps) = 1.00 + 0.88 * log(F0)",
                "sympy": "Eq(log(Ps), 1.00 + 0.88 * log(F0))",
                "variables": [
                    {"symbol": "Ps", "concept": "speech_0002", "role": "dependent"},
                    {"symbol": "F0", "concept": "speech_0001", "role": "independent"},
                ],
                "fit": {"r": 0.965, "r_sd": 0.04, "slope": 0.88, "slope_sd": 0.186},
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 19, "table": "Table 3"},
            },
            {
                "id": "claim_0009",
                "type": "parameter",
                "concept": "speech_0001",
                "value": [220.0],
                "unit": "Hz",
                "conditions": ["task == 'whisper'"],
                "provenance": {"paper": "test_paper_beta", "page": 22},
            },
        ],
    }

    (claims_dir / "test_paper_alpha.yaml").write_text(yaml.dump(alpha, default_flow_style=False))
    (claims_dir / "test_paper_beta.yaml").write_text(yaml.dump(beta, default_flow_style=False))

    from compiler.validate_claims import load_claim_files
    return load_claim_files(claims_dir)


@pytest.fixture
def sidecar_with_claims(concept_dir, sidecar_path, claim_files):
    """Build a sidecar that includes claim and conflict tables."""
    concepts = load_concepts(concept_dir)
    concept_registry = {c.data["id"]: c.data for c in concepts if c.data.get("id")}
    build_sidecar(concepts, sidecar_path, claim_files=claim_files, concept_registry=concept_registry)
    return sidecar_path


# ── Claim table ──────────────────────────────────────────────────────

class TestClaimTable:
    def test_claim_table_exists(self, sidecar_with_claims):
        """claim table created when claim_files provided."""
        conn = sqlite3.connect(sidecar_with_claims)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='claim'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_claim_count(self, sidecar_with_claims):
        """Correct number of claims in table."""
        conn = sqlite3.connect(sidecar_with_claims)
        count = conn.execute("SELECT COUNT(*) FROM claim").fetchone()[0]
        # 5 from alpha + 4 from beta = 9
        assert count == 9
        conn.close()

    def test_claim_fields(self, sidecar_with_claims):
        """Claim fields populated correctly."""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM claim WHERE id='claim_0001'").fetchone()
        assert row["type"] == "parameter"
        assert row["concept_id"] == "speech_0001"
        assert row["unit"] == "Hz"
        assert row["source_paper"] == "test_paper_alpha"
        assert row["provenance_page"] == 5
        conn.close()

    def test_parameter_claim_has_concept(self, sidecar_with_claims):
        """Parameter claim has concept_id populated."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT id, concept_id FROM claim WHERE type='parameter'"
        ).fetchall()
        for row in rows:
            assert row[1] is not None, f"claim {row[0]} missing concept_id"
        conn.close()

    def test_observation_claim_has_statement(self, sidecar_with_claims):
        """Observation claim has statement populated."""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM claim WHERE id='claim_0005'").fetchone()
        assert row["type"] == "observation"
        assert "logarithmic" in row["statement"]
        conn.close()

    def test_equation_claim_has_expression(self, sidecar_with_claims):
        """Equation claim has expression populated."""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM claim WHERE id='claim_0008'").fetchone()
        assert row["type"] == "equation"
        assert "log(Ps)" in row["expression"]
        conn.close()

    def test_no_claim_table_without_claims(self, concept_dir, sidecar_path):
        """claim table NOT created when claim_files is None."""
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='claim'")
        assert cursor.fetchone() is None
        conn.close()


# ── Conflicts table ──────────────────────────────────────────────────

class TestConflictsTable:
    def test_conflicts_table_exists(self, sidecar_with_claims):
        """conflicts table created when claim_files provided."""
        conn = sqlite3.connect(sidecar_with_claims)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='conflicts'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_conflict_detected(self, sidecar_with_claims):
        """CONFLICT record present for same-scope different-value claims."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT * FROM conflicts WHERE warning_class='CONFLICT'"
        ).fetchall()
        assert len(rows) >= 1
        conn.close()

    def test_conflict_query_by_class(self, sidecar_with_claims):
        """Can query: SELECT * FROM conflicts WHERE warning_class = 'CONFLICT'"""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM conflicts WHERE warning_class = 'CONFLICT'"
        ).fetchall()
        for row in rows:
            assert row["warning_class"] == "CONFLICT"
        assert len(rows) >= 1
        conn.close()

    def test_conflict_query_by_concept(self, sidecar_with_claims):
        """Can query: SELECT * FROM conflicts WHERE concept_id = 'speech_0001'"""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT * FROM conflicts WHERE concept_id = 'speech_0001'"
        ).fetchall()
        # speech_0001 has claims with different values under same/different conditions
        assert len(rows) >= 1
        conn.close()

    def test_phi_node_detected(self, sidecar_with_claims):
        """PHI_NODE record present for different-condition claims."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT * FROM conflicts WHERE warning_class='PHI_NODE'"
        ).fetchall()
        assert len(rows) >= 1
        conn.close()


# ── Claim FTS ────────────────────────────────────────────────────────

class TestClaimFTS:
    def test_claim_fts_search(self, sidecar_with_claims):
        """Can search claim statements via FTS."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT claim_id FROM claim_fts WHERE claim_fts MATCH 'logarithmic'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "claim_0005" in ids
        conn.close()

    def test_claim_fts_search_expression(self, sidecar_with_claims):
        """Can search claim expressions via FTS."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT claim_id FROM claim_fts WHERE claim_fts MATCH 'log'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "claim_0008" in ids
        conn.close()

    def test_claim_fts_search_conditions(self, sidecar_with_claims):
        """Can search claim conditions via FTS."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT claim_id FROM claim_fts WHERE claim_fts MATCH 'singing'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "claim_0003" in ids
        conn.close()
