"""Tests for the SQLite sidecar builder.

Verifies that the sidecar builder creates the correct tables,
populates them from concept YAML files, and builds the FTS5 index.
"""

import sqlite3

import pytest
import yaml

from propstore.build_sidecar import build_sidecar
from propstore.validate import load_concepts


@pytest.fixture
def concept_dir(tmp_path):
    """Create a concepts directory with a few test concepts."""
    knowledge = tmp_path / "knowledge"
    concepts_path = knowledge / "concepts"
    concepts_path.mkdir(parents=True)
    counters = concepts_path / ".counters"
    counters.mkdir()
    (counters / "speech.next").write_text("5")
    (counters / "narr.next").write_text("2")

    # Create form definition files
    forms_dir = knowledge / "forms"
    forms_dir.mkdir()
    for form_name in ("frequency", "category", "structural", "duration_ratio", "pressure"):
        (forms_dir / f"{form_name}.yaml").write_text(
            yaml.dump({"name": form_name}, default_flow_style=False))

    def write(name, data):
        (concepts_path / f"{name}.yaml").write_text(yaml.dump(data, default_flow_style=False))

    write("fundamental_frequency", {
        "id": "concept1",
        "canonical_name": "fundamental_frequency",
        "status": "accepted",
        "definition": "The rate of vocal fold vibration during phonation.",
        "domain": "speech",
        "created_date": "2026-03-15",
        "form": "frequency",
        "range": [50, 1000],
        "aliases": [
            {"name": "F0", "source": "common"},
            {"name": "pitch", "source": "common", "note": "perceptual correlate"},
        ],
        "relationships": [
            {"type": "broader", "target": "concept4"},
        ],
    })

    write("subglottal_pressure", {
        "id": "concept2",
        "canonical_name": "subglottal_pressure",
        "status": "accepted",
        "definition": "Air pressure below the glottis during phonation.",
        "domain": "speech",
        "form": "pressure",
        "aliases": [
            {"name": "Ps", "source": "Sundberg_1993"},
        ],
    })

    write("task", {
        "id": "concept3",
        "canonical_name": "task",
        "status": "accepted",
        "definition": "The vocal activity type used in an experiment.",
        "domain": "speech",
        "form": "category",
        "form_parameters": {"values": ["speech", "singing", "whisper"], "extensible": True},
    })

    write("voice_source", {
        "id": "concept4",
        "canonical_name": "voice_source",
        "status": "accepted",
        "definition": "The acoustic signal generated by the vibrating vocal folds.",
        "domain": "speech",
        "form": "structural",
        "relationships": [
            {"type": "narrower", "target": "concept1"},
            {"type": "narrower", "target": "concept2"},
        ],
    })

    write("return_phase_ratio", {
        "id": "concept5",
        "canonical_name": "return_phase_ratio",
        "status": "proposed",
        "definition": "Ratio of return phase time to fundamental period.",
        "domain": "speech",
        "form": "duration_ratio",
        "aliases": [
            {"name": "ra", "source": "Gobl_1988"},
            {"name": "Ra", "source": "Fant_1985", "note": "unnormalized"},
        ],
        "parameterization_relationships": [{
            "formula": "ra = ta / T0",
            "sympy": "Eq(ra, ta / T0)",
            "inputs": ["concept5", "concept1"],
            "exactness": "exact",
            "source": "Fant_1985",
            "bidirectional": True,
            "conditions": ["task == 'speech'"],
        }],
    })

    return concepts_path


@pytest.fixture
def repo(concept_dir):
    """Create a Repository pointing at the knowledge/ directory."""
    from propstore.cli.repository import Repository
    return Repository(concept_dir.parent)


@pytest.fixture
def sidecar_path(tmp_path):
    return tmp_path / "sidecar" / "propstore.sqlite"


# ── Table existence ──────────────────────────────────────────────────

class TestTableCreation:
    def test_creates_sqlite_file(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        assert sidecar_path.exists()

    def test_concept_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='concept'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_alias_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='alias'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_relationship_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='relationship'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_parameterization_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='parameterization'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_fts_table_exists(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='concept_fts'")
        assert cursor.fetchone() is not None
        conn.close()


# ── Concept table contents ───────────────────────────────────────────

class TestConceptTable:
    def test_concept_count(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        count = conn.execute("SELECT COUNT(*) FROM concept").fetchone()[0]
        assert count == 5
        conn.close()

    def test_concept_fields(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM concept WHERE id='concept1'").fetchone()
        assert row["canonical_name"] == "fundamental_frequency"
        assert row["status"] == "accepted"
        assert row["domain"] == "speech"
        assert row["kind_type"] == "quantity"
        assert "vocal fold" in row["definition"]
        conn.close()

    def test_proposed_concept_included(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute("SELECT status FROM concept WHERE id='concept5'").fetchone()
        assert row[0] == "proposed"
        conn.close()

    def test_concept_has_content_hash(self, concept_dir, sidecar_path):
        """Concepts have non-empty content_hash."""
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT content_hash FROM concept WHERE id='concept1'").fetchone()
        assert row["content_hash"] is not None
        assert len(row["content_hash"]) == 16
        conn.close()

    def test_concept_has_seq(self, concept_dir, sidecar_path):
        """Concepts have sequential numbering."""
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        seqs = [r[0] for r in conn.execute("SELECT seq FROM concept ORDER BY seq").fetchall()]
        assert seqs == list(range(1, len(seqs) + 1))
        conn.close()

    def test_content_hash_deterministic(self, concept_dir, sidecar_path):
        """Same content produces same hash across builds."""
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)
        hash1 = conn.execute("SELECT content_hash FROM concept WHERE id='concept1'").fetchone()[0]
        conn.close()

        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)
        hash2 = conn.execute("SELECT content_hash FROM concept WHERE id='concept1'").fetchone()[0]
        conn.close()
        assert hash1 == hash2


# ── Alias table contents ─────────────────────────────────────────────

class TestAliasTable:
    def test_alias_count(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        count = conn.execute("SELECT COUNT(*) FROM alias").fetchone()[0]
        # F0, pitch, Ps, ra, Ra = 5
        assert count == 5
        conn.close()

    def test_alias_lookup(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute(
            "SELECT concept_id FROM alias WHERE alias_name='F0'"
        ).fetchone()
        assert row[0] == "concept1"
        conn.close()

    def test_alias_source(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute(
            "SELECT source FROM alias WHERE alias_name='Ps'"
        ).fetchone()
        assert row[0] == "Sundberg_1993"
        conn.close()


# ── Relationship table contents ──────────────────────────────────────

class TestRelationshipTable:
    def test_relationship_count(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        count = conn.execute("SELECT COUNT(*) FROM relationship").fetchone()[0]
        # broader(concept1→concept4), narrower(concept4→concept1),
        # narrower(concept4→concept2) = 3
        assert count == 3
        conn.close()

    def test_relationship_fields(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT * FROM relationship WHERE source_id='concept1'"
        ).fetchone()
        assert row["type"] == "broader"
        assert row["target_id"] == "concept4"
        conn.close()


# ── Parameterization table contents ──────────────────────────────────

class TestParameterizationTable:
    def test_parameterization_count(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        count = conn.execute("SELECT COUNT(*) FROM parameterization").fetchone()[0]
        assert count == 1
        conn.close()

    def test_parameterization_fields(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM parameterization").fetchone()
        assert "concept5" in row["concept_ids"]
        assert row["formula"] == "ra = ta / T0"
        assert row["exactness"] == "exact"
        conn.close()

    def test_parameterization_has_output_concept_id(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM parameterization").fetchone()
        assert row["output_concept_id"] == "concept5"
        conn.close()


# ── FTS5 index ───────────────────────────────────────────────────────

class TestFTS:
    def test_fts_search_by_name(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        rows = conn.execute(
            "SELECT concept_id FROM concept_fts WHERE concept_fts MATCH 'frequency'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "concept1" in ids
        conn.close()

    def test_fts_search_by_alias(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        rows = conn.execute(
            "SELECT concept_id FROM concept_fts WHERE concept_fts MATCH 'pitch'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "concept1" in ids
        conn.close()

    def test_fts_search_by_definition(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        rows = conn.execute(
            "SELECT concept_id FROM concept_fts WHERE concept_fts MATCH 'glottis'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "concept2" in ids
        conn.close()

    def test_fts_search_by_condition(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        rows = conn.execute(
            "SELECT concept_id FROM concept_fts WHERE concept_fts MATCH 'speech'"
        ).fetchall()
        ids = [r[0] for r in rows]
        # return_phase_ratio has condition "task == 'speech'"
        assert "concept5" in ids
        conn.close()


# ── Rebuild skipping ─────────────────────────────────────────────────

class TestRebuildSkipping:
    def test_skip_rebuild_when_unchanged(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        mtime1 = sidecar_path.stat().st_mtime

        # Build again — should skip
        import time
        time.sleep(0.1)  # ensure different mtime if rebuilt
        build_sidecar(concepts, sidecar_path)
        mtime2 = sidecar_path.stat().st_mtime
        assert mtime1 == mtime2

    def test_rebuild_when_forced(self, concept_dir, sidecar_path):
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        mtime1 = sidecar_path.stat().st_mtime

        import time
        time.sleep(0.1)
        build_sidecar(concepts, sidecar_path, force=True)
        mtime2 = sidecar_path.stat().st_mtime
        assert mtime2 > mtime1


# ── Claim fixtures ───────────────────────────────────────────────────

@pytest.fixture
def claim_files(concept_dir):
    """Create claim files in a claims subdirectory alongside concepts."""
    claims_dir = concept_dir / "claims_data"
    claims_dir.mkdir(exist_ok=True)

    alpha = {
        "source": {"paper": "test_paper_alpha"},
        "claims": [
            {
                "id": "claim1",
                "type": "parameter",
                "concept": "concept1",
                "value": 200.0,
                "unit": "Hz",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 5},
            },
            {
                "id": "claim2",
                "type": "parameter",
                "concept": "concept1",
                "value": 350.0,
                "unit": "Hz",
                "conditions": ["task == 'speech'"],
                "stances": [
                    {
                        "type": "contradicts",
                        "target": "claim1",
                        "strength": "strong",
                        "note": "same task, conflicting value",
                    }
                ],
                "provenance": {"paper": "test_paper_alpha", "page": 8, "table": "Table 2"},
            },
            {
                "id": "claim3",
                "type": "parameter",
                "concept": "concept1",
                "value": 180.0,
                "unit": "Hz",
                "conditions": ["task == 'singing'"],
                "provenance": {"paper": "test_paper_alpha", "page": 12},
            },
            {
                "id": "claim4",
                "type": "parameter",
                "concept": "concept2",
                "value": 800.0,
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 15},
            },
            {
                "id": "claim5",
                "type": "observation",
                "statement": "Fundamental frequency increases with subglottal pressure in a roughly logarithmic relationship.",
                "concepts": ["concept1", "concept2"],
                "provenance": {"paper": "test_paper_alpha", "page": 20, "section": "Discussion"},
            },
        ],
    }

    beta = {
        "source": {"paper": "test_paper_beta"},
        "claims": [
            {
                "id": "claim6",
                "type": "parameter",
                "concept": "concept2",
                "value": 800.0,
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 3},
            },
            {
                "id": "claim7",
                "type": "parameter",
                "concept": "concept1",
                "value": 250.0,
                "unit": "Hz",
                "conditions": ["task == 'speech'", "fundamental_frequency > 100"],
                "provenance": {"paper": "test_paper_beta", "page": 7},
            },
            {
                "id": "claim8",
                "type": "equation",
                "expression": "log(Ps) = 1.00 + 0.88 * log(F0)",
                "sympy": "Eq(log(Ps), 1.00 + 0.88 * log(F0))",
                "variables": [
                    {"symbol": "Ps", "concept": "concept2", "role": "dependent"},
                    {"symbol": "F0", "concept": "concept1", "role": "independent"},
                ],
                "fit": {"r": 0.965, "r_sd": 0.04, "slope": 0.88, "slope_sd": 0.186},
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 19, "table": "Table 3"},
            },
            {
                "id": "claim9",
                "type": "parameter",
                "concept": "concept1",
                "value": 220.0,
                "unit": "Hz",
                "conditions": ["task == 'whisper'"],
                "provenance": {"paper": "test_paper_beta", "page": 22},
            },
        ],
    }

    (claims_dir / "test_paper_alpha.yaml").write_text(yaml.dump(alpha, default_flow_style=False))
    (claims_dir / "test_paper_beta.yaml").write_text(yaml.dump(beta, default_flow_style=False))

    from propstore.validate_claims import load_claim_files
    return load_claim_files(claims_dir)


@pytest.fixture
def sidecar_with_claims(concept_dir, sidecar_path, claim_files):
    """Build a sidecar that includes claim and conflict tables."""
    concepts = load_concepts(concept_dir)
    concept_registry = {c.data["id"]: c.data for c in concepts if c.data.get("id")}
    build_sidecar(concepts, sidecar_path, claim_files=claim_files, concept_registry=concept_registry)
    return sidecar_path


# ── Claim table ──────────────────────────────────────────────────────

class TestClaimTable:
    def test_claim_table_exists(self, sidecar_with_claims):
        """claim table created when claim_files provided."""
        conn = sqlite3.connect(sidecar_with_claims)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='claim'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_claim_count(self, sidecar_with_claims):
        """Correct number of claims in table."""
        conn = sqlite3.connect(sidecar_with_claims)
        count = conn.execute("SELECT COUNT(*) FROM claim").fetchone()[0]
        # 5 from alpha + 4 from beta = 9
        assert count == 9
        conn.close()

    def test_claim_fields(self, sidecar_with_claims):
        """Claim fields populated correctly."""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM claim WHERE id='claim1'").fetchone()
        assert row["type"] == "parameter"
        assert row["concept_id"] == "concept1"
        assert row["unit"] == "Hz"
        assert row["source_paper"] == "test_paper_alpha"
        assert row["provenance_page"] == 5
        conn.close()

    def test_claim_has_content_hash(self, sidecar_with_claims):
        """Claims have non-empty content_hash."""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT content_hash FROM claim WHERE id='claim1'").fetchone()
        assert row["content_hash"] is not None
        assert len(row["content_hash"]) == 16
        conn.close()

    def test_claim_has_seq(self, sidecar_with_claims):
        """Claims have sequential numbering."""
        conn = sqlite3.connect(sidecar_with_claims)
        seqs = [r[0] for r in conn.execute("SELECT seq FROM claim ORDER BY seq").fetchall()]
        assert seqs == list(range(1, len(seqs) + 1))
        conn.close()

    def test_claim_has_auto_summary(self, sidecar_with_claims):
        """Parameter claims get auto_summary from description_generator."""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT auto_summary FROM claim WHERE id='claim1'").fetchone()
        assert row["auto_summary"] is not None
        assert "fundamental_frequency" in row["auto_summary"]
        conn.close()

    def test_claim_description_from_yaml(self, sidecar_with_claims):
        """description column is None when not in YAML (LLM-written field)."""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT description FROM claim WHERE id='claim1'").fetchone()
        assert row["description"] is None
        conn.close()

    def test_parameter_claim_has_concept(self, sidecar_with_claims):
        """Parameter claim has concept_id populated."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT id, concept_id FROM claim WHERE type='parameter'"
        ).fetchall()
        for row in rows:
            assert row[1] is not None, f"claim {row[0]} missing concept_id"
        conn.close()

    def test_observation_claim_has_statement(self, sidecar_with_claims):
        """Observation claim has statement populated."""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM claim WHERE id='claim5'").fetchone()
        assert row["type"] == "observation"
        assert "logarithmic" in row["statement"]
        conn.close()

    def test_equation_claim_has_expression(self, sidecar_with_claims):
        """Equation claim has expression populated."""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM claim WHERE id='claim8'").fetchone()
        assert row["type"] == "equation"
        assert "log(Ps)" in row["expression"]
        conn.close()

    def test_equation_claim_preserves_sympy_error(self, concept_dir, sidecar_path, repo):
        """Equation claims preserve the auto-generation error when sympy cannot be derived."""
        claims_dir = concept_dir / "claims_equation_error"
        claims_dir.mkdir(exist_ok=True)
        claim_data = {
            "source": {"paper": "equation_error_paper"},
            "claims": [
                {
                    "id": "claim1",
                    "type": "equation",
                    "expression": "F0 is roughly proportional to Ps",
                    "variables": [
                        {"symbol": "F0", "concept": "concept1"},
                        {"symbol": "Ps", "concept": "concept2"},
                    ],
                    "provenance": {"paper": "equation_error_paper", "page": 1},
                },
            ],
        }
        (claims_dir / "equation_error_paper.yaml").write_text(
            yaml.dump(claim_data, default_flow_style=False)
        )

        from propstore.validate_claims import build_concept_registry, load_claim_files

        claim_files = load_claim_files(claims_dir)
        concepts = load_concepts(concept_dir)
        concept_registry = build_concept_registry(repo)
        build_sidecar(
            concepts,
            sidecar_path,
            force=True,
            claim_files=claim_files,
            concept_registry=concept_registry,
        )

        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT sympy_generated, sympy_error FROM claim WHERE id='claim1'"
        ).fetchone()
        assert row["sympy_generated"] is None
        assert row["sympy_error"] is not None
        conn.close()

    def test_legacy_list_value_raises(self, concept_dir, sidecar_path, repo):
        """Legacy list value format raises TypeError — no silent conversion."""
        claims_dir = concept_dir / "claims_range"
        claims_dir.mkdir(exist_ok=True)
        claim_data = {
            "source": {"paper": "range_paper"},
            "claims": [
                {
                    "id": "claim1",
                    "type": "parameter",
                    "concept": "concept1",
                    "value": [100.0, 300.0],
                    "unit": "Hz",
                    "provenance": {"paper": "range_paper", "page": 1},
                },
            ],
        }
        (claims_dir / "range_paper.yaml").write_text(yaml.dump(claim_data, default_flow_style=False))

        from propstore.validate_claims import load_claim_files, build_concept_registry

        claim_files = load_claim_files(claims_dir)
        concepts = load_concepts(concept_dir)
        concept_registry = build_concept_registry(repo)
        with pytest.raises(TypeError):
            build_sidecar(concepts, sidecar_path, force=True,
                          claim_files=claim_files, concept_registry=concept_registry)

    def test_proper_bounds_without_value(self, concept_dir, sidecar_path, repo):
        """Proper bounds format (lower_bound + upper_bound, no value) stores correctly."""
        claims_dir = concept_dir / "claims_bounds"
        claims_dir.mkdir(exist_ok=True)
        claim_data = {
            "source": {"paper": "bounds_paper"},
            "claims": [
                {
                    "id": "claim1",
                    "type": "parameter",
                    "concept": "concept1",
                    "lower_bound": 100.0,
                    "upper_bound": 300.0,
                    "unit": "Hz",
                    "provenance": {"paper": "bounds_paper", "page": 1},
                },
            ],
        }
        (claims_dir / "bounds_paper.yaml").write_text(yaml.dump(claim_data, default_flow_style=False))

        from propstore.validate_claims import load_claim_files, build_concept_registry

        claim_files = load_claim_files(claims_dir)
        concepts = load_concepts(concept_dir)
        concept_registry = build_concept_registry(repo)
        build_sidecar(concepts, sidecar_path, force=True,
                      claim_files=claim_files, concept_registry=concept_registry)

        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT value, lower_bound, upper_bound FROM claim WHERE id='claim1'").fetchone()
        assert row["value"] is None
        assert row["lower_bound"] == 100.0
        assert row["upper_bound"] == 300.0
        conn.close()

    def test_no_claim_table_without_claims(self, concept_dir, sidecar_path):
        """claim table NOT created when claim_files is None."""
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='claim'")
        assert cursor.fetchone() is None
        conn.close()


# ── Conflicts table ──────────────────────────────────────────────────

class TestConflictsTable:
    def test_conflicts_table_exists(self, sidecar_with_claims):
        """conflicts table created when claim_files provided."""
        conn = sqlite3.connect(sidecar_with_claims)
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='conflicts'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_conflict_detected(self, sidecar_with_claims):
        """CONFLICT record present for same-scope different-value claims."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT * FROM conflicts WHERE warning_class='CONFLICT'"
        ).fetchall()
        assert len(rows) >= 1
        conn.close()


class TestClaimStanceTable:
    def test_claim_stance_table_exists(self, sidecar_with_claims):
        conn = sqlite3.connect(sidecar_with_claims)
        cursor = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='claim_stance'"
        )
        assert cursor.fetchone() is not None
        conn.close()

    def test_claim_stance_rows_persisted(self, sidecar_with_claims):
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT claim_id, target_claim_id, stance_type, strength, note "
            "FROM claim_stance WHERE claim_id='claim2'"
        ).fetchone()
        assert row["claim_id"] == "claim2"
        assert row["target_claim_id"] == "claim1"
        assert row["stance_type"] == "contradicts"
        assert row["strength"] == "strong"
        assert "conflicting value" in row["note"]
        conn.close()

    def test_conflict_query_by_class(self, sidecar_with_claims):
        """Can query: SELECT * FROM conflicts WHERE warning_class = 'CONFLICT'"""
        conn = sqlite3.connect(sidecar_with_claims)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM conflicts WHERE warning_class = 'CONFLICT'"
        ).fetchall()
        for row in rows:
            assert row["warning_class"] == "CONFLICT"
        assert len(rows) >= 1
        conn.close()

    def test_conflict_query_by_concept(self, sidecar_with_claims):
        """Can query: SELECT * FROM conflicts WHERE concept_id = 'concept1'"""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT * FROM conflicts WHERE concept_id = 'concept1'"
        ).fetchall()
        # concept1 has claims with different values under same/different conditions
        assert len(rows) >= 1
        conn.close()

    def test_phi_node_detected(self, sidecar_with_claims):
        """PHI_NODE record present for different-condition claims."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT * FROM conflicts WHERE warning_class='PHI_NODE'"
        ).fetchall()
        assert len(rows) >= 1
        conn.close()


# ── Claim FTS ────────────────────────────────────────────────────────

class TestClaimFTS:
    def test_claim_fts_search(self, sidecar_with_claims):
        """Can search claim statements via FTS."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT claim_id FROM claim_fts WHERE claim_fts MATCH 'logarithmic'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "claim5" in ids
        conn.close()

    def test_claim_fts_search_expression(self, sidecar_with_claims):
        """Can search claim expressions via FTS."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT claim_id FROM claim_fts WHERE claim_fts MATCH 'log'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "claim8" in ids
        conn.close()

    def test_claim_fts_search_conditions(self, sidecar_with_claims):
        """Can search claim conditions via FTS."""
        conn = sqlite3.connect(sidecar_with_claims)
        rows = conn.execute(
            "SELECT claim_id FROM claim_fts WHERE claim_fts MATCH 'singing'"
        ).fetchall()
        ids = [r[0] for r in rows]
        assert "claim3" in ids
        conn.close()


# ── Parameterization group table ────────────────────────────────────

class TestParameterizationGroupTable:
    def test_parameterization_group_table_exists(self, concept_dir, sidecar_path):
        """parameterization_group table created during build."""
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)
        cursor = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='parameterization_group'")
        assert cursor.fetchone() is not None
        conn.close()

    def test_parameterization_groups_reflect_components(self, concept_dir, sidecar_path):
        """Groups reflect connected components from parameterizations."""
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)

        # Concepts with parameterization links should share a group
        rows = conn.execute(
            "SELECT concept_id, group_id FROM parameterization_group"
        ).fetchall()
        by_group = {}
        for cid, gid in rows:
            by_group.setdefault(gid, set()).add(cid)

        # concept5 (return_phase_ratio) has parameterization with inputs [concept5, concept1]
        # So concept1 and concept5 should be in the same group
        found = False
        for gid, members in by_group.items():
            if "concept1" in members and "concept5" in members:
                found = True
                break
        assert found, f"concept1 and concept5 should be in the same parameterization group. Groups: {by_group}"

        conn.close()


# ── Concept form metadata ────────────────────────────────────────────

class TestConceptFormMetadata:
    def _setup_forms(self, concept_dir):
        """Write real form definitions for the test concepts."""
        forms_dir = concept_dir.parent / "forms"
        forms_dir.mkdir(exist_ok=True)
        yaml.dump({"name": "frequency", "unit_symbol": "Hz"},
                  (forms_dir / "frequency.yaml").open("w"))
        yaml.dump({"name": "pressure", "unit_symbol": "Pa",
                   "common_alternatives": [{"unit": "cmH2O", "type": "multiplicative", "multiplier": 98.0665}]},
                  (forms_dir / "pressure.yaml").open("w"))
        yaml.dump({"name": "category", "parameters": {"values": [], "extensible": False}},
                  (forms_dir / "category.yaml").open("w"))
        yaml.dump({"name": "structural", "note": "Non-measurable organizing concepts."},
                  (forms_dir / "structural.yaml").open("w"))
        yaml.dump({"name": "duration_ratio", "base": "ratio",
                   "parameters": {"numerator": "duration", "denominator": "duration"}},
                  (forms_dir / "duration_ratio.yaml").open("w"))

    def test_concept_has_is_dimensionless_column(self, concept_dir, sidecar_path):
        self._setup_forms(concept_dir)
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM concept WHERE id='concept1'").fetchone()
        assert "is_dimensionless" in row.keys()
        conn.close()

    def test_frequency_concept_not_dimensionless(self, concept_dir, sidecar_path):
        self._setup_forms(concept_dir)
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute("SELECT is_dimensionless FROM concept WHERE id='concept1'").fetchone()
        assert row[0] == 0
        conn.close()

    def test_ratio_concept_is_dimensionless(self, concept_dir, sidecar_path):
        self._setup_forms(concept_dir)
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute("SELECT is_dimensionless FROM concept WHERE id='concept5'").fetchone()
        assert row[0] == 1
        conn.close()

    def test_concept_has_unit_symbol_column(self, concept_dir, sidecar_path):
        self._setup_forms(concept_dir)
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)
        conn.row_factory = sqlite3.Row
        row = conn.execute("SELECT * FROM concept WHERE id='concept1'").fetchone()
        assert "unit_symbol" in row.keys()
        conn.close()

    def test_frequency_concept_unit_symbol(self, concept_dir, sidecar_path):
        self._setup_forms(concept_dir)
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute("SELECT unit_symbol FROM concept WHERE id='concept1'").fetchone()
        assert row[0] == "Hz"
        conn.close()

    def test_ratio_concept_unit_symbol_null(self, concept_dir, sidecar_path):
        self._setup_forms(concept_dir)
        concepts = load_concepts(concept_dir)
        build_sidecar(concepts, sidecar_path, force=True)
        conn = sqlite3.connect(sidecar_path)
        row = conn.execute("SELECT unit_symbol FROM concept WHERE id='concept5'").fetchone()
        assert row[0] is None
        conn.close()
