"""Tests for WorldModel — condition-binding reasoner over compiled sidecar.

TDD tests (Phases 1-2 from design doc):
- Construction, unbound queries, explain, bind/active_claims, value_of, bound conflicts
- Hypothesis property tests for invariants
"""

import json
import sqlite3

import pytest
import yaml

from compiler.build_sidecar import build_sidecar
from compiler.validate import load_concepts
from compiler.world_model import BoundWorld, ValueResult, WorldModel


# ── Fixtures ─────────────────────────────────────────────────────────
# Reuse the concept_dir + claim_files pattern from test_build_sidecar.py


@pytest.fixture
def concept_dir(tmp_path):
    """Create a concepts directory with test concepts."""
    knowledge = tmp_path / "knowledge"
    concepts_path = knowledge / "concepts"
    concepts_path.mkdir(parents=True)
    counters = concepts_path / ".counters"
    counters.mkdir()
    (counters / "speech.next").write_text("5")

    forms_dir = knowledge / "forms"
    forms_dir.mkdir()
    for form_name in ("frequency", "category", "structural", "duration_ratio", "pressure"):
        (forms_dir / f"{form_name}.yaml").write_text(
            yaml.dump({"name": form_name}, default_flow_style=False))

    def write(name, data):
        (concepts_path / f"{name}.yaml").write_text(yaml.dump(data, default_flow_style=False))

    write("fundamental_frequency", {
        "id": "concept1",
        "canonical_name": "fundamental_frequency",
        "status": "accepted",
        "definition": "The rate of vocal fold vibration during phonation.",
        "domain": "speech",
        "created_date": "2026-03-15",
        "form": "frequency",
        "range": [50, 1000],
        "aliases": [
            {"name": "F0", "source": "common"},
            {"name": "pitch", "source": "common", "note": "perceptual correlate"},
        ],
        "relationships": [
            {"type": "broader", "target": "concept4"},
        ],
    })

    write("subglottal_pressure", {
        "id": "concept2",
        "canonical_name": "subglottal_pressure",
        "status": "accepted",
        "definition": "Air pressure below the glottis during phonation.",
        "domain": "speech",
        "form": "pressure",
        "aliases": [
            {"name": "Ps", "source": "Sundberg_1993"},
        ],
    })

    write("task", {
        "id": "concept3",
        "canonical_name": "task",
        "status": "accepted",
        "definition": "The vocal activity type used in an experiment.",
        "domain": "speech",
        "form": "category",
        "form_parameters": {"values": ["speech", "singing", "whisper"], "extensible": True},
    })

    write("voice_source", {
        "id": "concept4",
        "canonical_name": "voice_source",
        "status": "accepted",
        "definition": "The acoustic signal generated by the vibrating vocal folds.",
        "domain": "speech",
        "form": "structural",
        "relationships": [
            {"type": "narrower", "target": "concept1"},
            {"type": "narrower", "target": "concept2"},
        ],
    })

    write("return_phase_ratio", {
        "id": "concept5",
        "canonical_name": "return_phase_ratio",
        "status": "proposed",
        "definition": "Ratio of return phase time to fundamental period.",
        "domain": "speech",
        "form": "duration_ratio",
        "aliases": [
            {"name": "ra", "source": "Gobl_1988"},
            {"name": "Ra", "source": "Fant_1985", "note": "unnormalized"},
        ],
        "parameterization_relationships": [{
            "formula": "ra = ta / T0",
            "sympy": "Eq(ra, ta / T0)",
            "inputs": ["concept5", "concept1"],
            "exactness": "exact",
            "source": "Fant_1985",
            "bidirectional": True,
            "conditions": ["task == 'speech'"],
        }],
    })

    return concepts_path


@pytest.fixture
def repo(concept_dir):
    from compiler.cli.repository import Repository
    return Repository(concept_dir.parent)


@pytest.fixture
def claim_files(concept_dir):
    """Create claim files with known conditions for binding tests."""
    claims_dir = concept_dir / "claims_data"
    claims_dir.mkdir(exist_ok=True)

    alpha = {
        "source": {"paper": "test_paper_alpha"},
        "claims": [
            {
                "id": "claim1",
                "type": "parameter",
                "concept": "concept1",
                "value": 200.0,
                "unit": "Hz",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 5},
            },
            {
                "id": "claim2",
                "type": "parameter",
                "concept": "concept1",
                "value": 350.0,
                "unit": "Hz",
                "conditions": ["task == 'speech'"],
                "stances": [
                    {
                        "type": "contradicts",
                        "target": "claim1",
                        "strength": "strong",
                        "note": "same task, conflicting value",
                    }
                ],
                "provenance": {"paper": "test_paper_alpha", "page": 8},
            },
            {
                "id": "claim3",
                "type": "parameter",
                "concept": "concept1",
                "value": 180.0,
                "unit": "Hz",
                "conditions": ["task == 'singing'"],
                "provenance": {"paper": "test_paper_alpha", "page": 12},
            },
            {
                "id": "claim4",
                "type": "parameter",
                "concept": "concept2",
                "value": 800.0,
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 15},
            },
            {
                "id": "claim5",
                "type": "observation",
                "statement": "F0 increases with Ps logarithmically.",
                "concepts": ["concept1", "concept2"],
                "provenance": {"paper": "test_paper_alpha", "page": 20},
            },
        ],
    }

    beta = {
        "source": {"paper": "test_paper_beta"},
        "claims": [
            {
                "id": "claim6",
                "type": "parameter",
                "concept": "concept2",
                "value": 800.0,
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 3},
            },
            {
                "id": "claim7",
                "type": "parameter",
                "concept": "concept1",
                "value": 250.0,
                "unit": "Hz",
                "conditions": ["task == 'speech'", "fundamental_frequency > 100"],
                "provenance": {"paper": "test_paper_beta", "page": 7},
            },
            {
                "id": "claim8",
                "type": "equation",
                "expression": "log(Ps) = 1.00 + 0.88 * log(F0)",
                "sympy": "Eq(log(Ps), 1.00 + 0.88 * log(F0))",
                "variables": [
                    {"symbol": "Ps", "concept": "concept2", "role": "dependent"},
                    {"symbol": "F0", "concept": "concept1", "role": "independent"},
                ],
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 19},
            },
            {
                "id": "claim9",
                "type": "parameter",
                "concept": "concept1",
                "value": 220.0,
                "unit": "Hz",
                "conditions": ["task == 'whisper'"],
                "provenance": {"paper": "test_paper_beta", "page": 22},
            },
        ],
    }

    (claims_dir / "test_paper_alpha.yaml").write_text(yaml.dump(alpha, default_flow_style=False))
    (claims_dir / "test_paper_beta.yaml").write_text(yaml.dump(beta, default_flow_style=False))

    from compiler.validate_claims import load_claim_files
    return load_claim_files(claims_dir)


@pytest.fixture
def world(concept_dir, repo, claim_files):
    """Build sidecar and return a WorldModel."""
    concepts = load_concepts(concept_dir)
    concept_registry = {c.data["id"]: c.data for c in concepts if c.data.get("id")}
    build_sidecar(concepts, repo.sidecar_path, claim_files=claim_files,
                  concept_registry=concept_registry, repo=repo)
    return WorldModel(repo)


# ── Construction ─────────────────────────────────────────────────────

class TestWorldModelConstruction:
    def test_construct_from_repo(self, world):
        assert world is not None

    def test_raises_without_sidecar(self, tmp_path):
        from compiler.cli.repository import Repository
        repo = Repository.init(tmp_path / "empty_knowledge")
        with pytest.raises(FileNotFoundError):
            WorldModel(repo)

    def test_context_manager(self, world):
        with world:
            assert world.get_concept("concept1") is not None


# ── Unbound queries ──────────────────────────────────────────────────

class TestUnboundQueries:
    def test_get_concept(self, world):
        c = world.get_concept("concept1")
        assert c is not None
        assert c["canonical_name"] == "fundamental_frequency"

    def test_get_concept_missing(self, world):
        assert world.get_concept("nonexistent") is None

    def test_get_claim(self, world):
        c = world.get_claim("claim1")
        assert c is not None
        assert c["type"] == "parameter"
        assert c["concept_id"] == "concept1"

    def test_get_claim_missing(self, world):
        assert world.get_claim("nonexistent") is None

    def test_resolve_alias(self, world):
        assert world.resolve_alias("F0") == "concept1"
        assert world.resolve_alias("Ps") == "concept2"

    def test_resolve_alias_missing(self, world):
        assert world.resolve_alias("nonexistent") is None

    def test_claims_for(self, world):
        claims = world.claims_for("concept1")
        ids = {c["id"] for c in claims}
        # claim1, claim2, claim3, claim7, claim9 all target concept1
        assert ids == {"claim1", "claim2", "claim3", "claim7", "claim9"}

    def test_claims_for_missing(self, world):
        assert world.claims_for("nonexistent") == []

    def test_conflicts(self, world):
        conflicts = world.conflicts()
        assert len(conflicts) >= 1
        # Should have warning_class field
        assert all("warning_class" in c for c in conflicts)

    def test_search(self, world):
        results = world.search("frequency")
        ids = [r["concept_id"] for r in results]
        assert "concept1" in ids

    def test_stats(self, world):
        s = world.stats()
        assert s["concepts"] == 5
        assert s["claims"] == 9
        assert s["conflicts"] >= 1


# ── Explain (stance graph) ───────────────────────────────────────────

class TestExplain:
    def test_explain_returns_stance_chain(self, world):
        chain = world.explain("claim2")
        # claim2 has a stance: contradicts claim1
        assert len(chain) >= 1
        assert chain[0]["target_claim_id"] == "claim1"
        assert chain[0]["stance_type"] == "contradicts"

    def test_explain_no_stances(self, world):
        chain = world.explain("claim1")
        # claim1 has no outgoing stances
        assert chain == []

    def test_explain_missing_claim(self, world):
        chain = world.explain("nonexistent")
        assert chain == []


# ── Bind and active claims ───────────────────────────────────────────

class TestBindAndActiveClaims:
    def test_bind_returns_bound_world(self, world):
        bound = world.bind(task="speech")
        assert isinstance(bound, BoundWorld)

    def test_bind_speech_activates_speech_claims(self, world):
        bound = world.bind(task="speech")
        active = bound.active_claims("concept1")
        active_ids = {c["id"] for c in active}
        # claim1, claim2 (task=='speech'), claim7 (task=='speech' + f0>100) should be active
        assert "claim1" in active_ids
        assert "claim2" in active_ids
        assert "claim7" in active_ids
        # claim3 (singing) and claim9 (whisper) should NOT be active
        assert "claim3" not in active_ids
        assert "claim9" not in active_ids

    def test_bind_singing_activates_singing_claims(self, world):
        bound = world.bind(task="singing")
        active = bound.active_claims("concept1")
        active_ids = {c["id"] for c in active}
        assert "claim3" in active_ids
        # speech claims should NOT be active
        assert "claim1" not in active_ids
        assert "claim2" not in active_ids

    def test_bind_whisper_activates_whisper_claims(self, world):
        bound = world.bind(task="whisper")
        active = bound.active_claims("concept1")
        active_ids = {c["id"] for c in active}
        assert "claim9" in active_ids
        assert "claim1" not in active_ids
        assert "claim3" not in active_ids

    def test_unconditional_claims_always_active(self, world):
        """Claims with no conditions are active under any binding."""
        bound = world.bind(task="speech")
        active = bound.active_claims()
        active_ids = {c["id"] for c in active}
        # claim5 is an observation with no conditions
        assert "claim5" in active_ids

    def test_empty_bind_all_active(self, world):
        """Empty bindings → all claims active."""
        bound = world.bind()
        active = bound.active_claims()
        assert len(active) == 9

    def test_inactive_claims(self, world):
        bound = world.bind(task="singing")
        inactive = bound.inactive_claims("concept1")
        inactive_ids = {c["id"] for c in inactive}
        # speech and whisper claims should be inactive
        assert "claim1" in inactive_ids
        assert "claim2" in inactive_ids
        assert "claim9" in inactive_ids

    def test_active_claims_all_concepts(self, world):
        """active_claims(None) returns claims across all concepts."""
        bound = world.bind(task="speech")
        active = bound.active_claims()
        # Should include concept1 speech claims + concept2 speech claims + unconditional claim5
        active_ids = {c["id"] for c in active}
        assert "claim4" in active_ids  # concept2, task=='speech'
        assert "claim6" in active_ids  # concept2, task=='speech'


# ── value_of ─────────────────────────────────────────────────────────

class TestValueOf:
    def test_singing_determined(self, world):
        """Under task='singing', concept1 has one claim → determined."""
        bound = world.bind(task="singing")
        result = bound.value_of("concept1")
        assert isinstance(result, ValueResult)
        assert result.status == "determined"
        assert len(result.claims) == 1
        assert result.claims[0]["id"] == "claim3"

    def test_speech_conflicted(self, world):
        """Under task='speech', concept1 has multiple claims with different values → conflicted."""
        bound = world.bind(task="speech")
        result = bound.value_of("concept1")
        assert result.status == "conflicted"
        assert len(result.claims) >= 2

    def test_no_claims(self, world):
        """Concept with no claims → no_claims."""
        bound = world.bind(task="speech")
        result = bound.value_of("concept3")  # task concept — no parameter claims
        assert result.status == "no_claims"

    def test_is_determined(self, world):
        bound = world.bind(task="singing")
        assert bound.is_determined("concept1") is True

    def test_is_not_determined(self, world):
        bound = world.bind(task="speech")
        assert bound.is_determined("concept1") is False


# ── Bound conflicts ──────────────────────────────────────────────────

class TestBoundConflicts:
    def test_singing_no_conflicts_concept1(self, world):
        """Under singing, concept1 has only claim3 → no conflicts."""
        bound = world.bind(task="singing")
        conflicts = bound.conflicts("concept1")
        assert len(conflicts) == 0

    def test_speech_has_conflicts_concept1(self, world):
        """Under speech, concept1 has claim1(200), claim2(350), claim7(250) → conflicts."""
        bound = world.bind(task="speech")
        conflicts = bound.conflicts("concept1")
        assert len(conflicts) >= 1

    def test_speech_no_conflicts_concept2(self, world):
        """Under speech, concept2 has claim4(800) and claim6(800) — same value → no conflicts."""
        bound = world.bind(task="speech")
        conflicts = bound.conflicts("concept2")
        # Both claims have value 800 — COMPATIBLE, not returned
        assert len(conflicts) == 0


# ── Bound explain ────────────────────────────────────────────────────

class TestBoundExplain:
    def test_explain_filtered_to_active(self, world):
        """Under singing, explain(claim2) returns empty — claim2 is inactive."""
        bound = world.bind(task="singing")
        chain = bound.explain("claim2")
        # claim2 is inactive under singing, so explain returns nothing
        assert chain == []


# ── Hypothesis property tests ────────────────────────────────────────

class TestHypothesisProperties:
    def test_unconditional_always_active(self, world):
        """Unconditional claims are active under any binding."""
        for binding in [
            {},
            {"task": "speech"},
            {"task": "singing"},
            {"task": "whisper"},
        ]:
            bound = world.bind(**binding)
            active_ids = {c["id"] for c in bound.active_claims()}
            # claim5 has no conditions — always active
            assert "claim5" in active_ids, f"claim5 not active under {binding}"

    def test_partitioning(self, world):
        """active ∪ inactive = all claims, for any binding."""
        all_claims = {c["id"] for c in world.claims_for(None)}
        for binding in [
            {},
            {"task": "speech"},
            {"task": "singing"},
            {"task": "whisper"},
        ]:
            bound = world.bind(**binding)
            active = {c["id"] for c in bound.active_claims()}
            inactive = {c["id"] for c in bound.inactive_claims()}
            assert active | inactive == all_claims, f"Partition violated under {binding}"
            assert active & inactive == set(), f"Overlap in partition under {binding}"

    def test_monotonicity(self, world):
        """More bindings → fewer or equal active claims."""
        broad = world.bind(task="speech")
        narrow = world.bind(task="speech", fundamental_frequency=200)
        broad_ids = {c["id"] for c in broad.active_claims()}
        narrow_ids = {c["id"] for c in narrow.active_claims()}
        assert narrow_ids <= broad_ids, (
            f"Monotonicity violated: narrow has {narrow_ids - broad_ids} not in broad"
        )

    def test_conflict_subsetting(self, world):
        """Bound conflicts ⊆ world conflicts (binding can only remove conflicts)."""
        world_conflict_pairs = {
            (c["claim_a_id"], c["claim_b_id"]) for c in world.conflicts()
        }
        for binding in [
            {"task": "speech"},
            {"task": "singing"},
            {"task": "whisper"},
        ]:
            bound = world.bind(**binding)
            bound_conflict_pairs = {
                (c["claim_a_id"], c["claim_b_id"]) for c in bound.conflicts()
            }
            assert bound_conflict_pairs <= world_conflict_pairs, (
                f"Bound conflicts not subset under {binding}: "
                f"{bound_conflict_pairs - world_conflict_pairs}"
            )

    def test_determinism(self, world):
        """Same bindings → same results."""
        r1 = world.bind(task="speech").active_claims()
        r2 = world.bind(task="speech").active_claims()
        ids1 = sorted(c["id"] for c in r1)
        ids2 = sorted(c["id"] for c in r2)
        assert ids1 == ids2
