"""Tests for graph_export — KnowledgeGraph construction and serialization."""

import sqlite3

import pytest
import yaml

from propstore.build_sidecar import build_sidecar
from propstore.graph_export import GraphEdge, GraphNode, KnowledgeGraph, build_knowledge_graph
from propstore.validate import load_concepts
from propstore.world import WorldModel


# ── Fixtures (duplicated from test_world_model.py) ────────────────────


@pytest.fixture
def concept_dir(tmp_path):
    """Create a concepts directory with test concepts."""
    knowledge = tmp_path / "knowledge"
    concepts_path = knowledge / "concepts"
    concepts_path.mkdir(parents=True)
    counters = concepts_path / ".counters"
    counters.mkdir()
    (counters / "speech.next").write_text("5")

    forms_dir = knowledge / "forms"
    forms_dir.mkdir()
    for form_name in ("frequency", "category", "structural", "duration_ratio",
                      "pressure", "time"):
        (forms_dir / f"{form_name}.yaml").write_text(
            yaml.dump({"name": form_name}, default_flow_style=False))

    def write(name, data):
        (concepts_path / f"{name}.yaml").write_text(yaml.dump(data, default_flow_style=False))

    write("fundamental_frequency", {
        "id": "concept1",
        "canonical_name": "fundamental_frequency",
        "status": "accepted",
        "definition": "The rate of vocal fold vibration during phonation.",
        "domain": "speech",
        "created_date": "2026-03-15",
        "form": "frequency",
        "range": [50, 1000],
        "aliases": [
            {"name": "F0", "source": "common"},
            {"name": "pitch", "source": "common", "note": "perceptual correlate"},
        ],
        "relationships": [
            {"type": "broader", "target": "concept4"},
        ],
    })

    write("subglottal_pressure", {
        "id": "concept2",
        "canonical_name": "subglottal_pressure",
        "status": "accepted",
        "definition": "Air pressure below the glottis during phonation.",
        "domain": "speech",
        "form": "pressure",
        "aliases": [
            {"name": "Ps", "source": "Sundberg_1993"},
        ],
    })

    write("task", {
        "id": "concept3",
        "canonical_name": "task",
        "status": "accepted",
        "definition": "The vocal activity type used in an experiment.",
        "domain": "speech",
        "form": "category",
        "form_parameters": {"values": ["speech", "singing", "whisper"], "extensible": True},
    })

    write("voice_source", {
        "id": "concept4",
        "canonical_name": "voice_source",
        "status": "accepted",
        "definition": "The acoustic signal generated by the vibrating vocal folds.",
        "domain": "speech",
        "form": "structural",
        "relationships": [
            {"type": "narrower", "target": "concept1"},
            {"type": "narrower", "target": "concept2"},
        ],
    })

    write("return_phase_ratio", {
        "id": "concept5",
        "canonical_name": "return_phase_ratio",
        "status": "proposed",
        "definition": "Ratio of return phase time to fundamental period.",
        "domain": "speech",
        "form": "duration_ratio",
        "aliases": [
            {"name": "ra", "source": "Gobl_1988"},
            {"name": "Ra", "source": "Fant_1985", "note": "unnormalized"},
        ],
        "parameterization_relationships": [{
            "formula": "ra = ta * F0",
            "sympy": "Eq(concept5, concept6 * concept1)",
            "inputs": ["concept6", "concept1"],
            "exactness": "exact",
            "source": "Fant_1985",
            "bidirectional": True,
            "conditions": ["task == 'speech'"],
        }],
    })

    write("return_phase_time", {
        "id": "concept6",
        "canonical_name": "return_phase_time",
        "status": "proposed",
        "definition": "Duration of the return phase of the glottal cycle.",
        "domain": "speech",
        "form": "time",
        "aliases": [
            {"name": "ta", "source": "Fant_1985"},
        ],
    })

    write("derived_ratio", {
        "id": "concept7",
        "canonical_name": "derived_ratio",
        "status": "proposed",
        "definition": "A ratio derived from return_phase_ratio for testing chains.",
        "domain": "speech",
        "form": "duration_ratio",
        "parameterization_relationships": [{
            "formula": "dr = 2 * ra",
            "sympy": "Eq(concept7, 2 * concept5)",
            "inputs": ["concept5"],
            "exactness": "exact",
            "source": "test",
            "conditions": ["task == 'speech'"],
        }],
    })

    return concepts_path


@pytest.fixture
def repo(concept_dir):
    from propstore.cli.repository import Repository
    return Repository(concept_dir.parent)


@pytest.fixture
def claim_files(concept_dir):
    """Create claim files with known conditions for binding tests."""
    claims_dir = concept_dir / "claims_data"
    claims_dir.mkdir(exist_ok=True)

    alpha = {
        "source": {"paper": "test_paper_alpha"},
        "claims": [
            {
                "id": "claim1",
                "type": "parameter",
                "concept": "concept1",
                "value": 200.0,
                "unit": "Hz",
                "sample_size": 30,
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 5,
                               "date": "2024-01-15"},
            },
            {
                "id": "claim2",
                "type": "parameter",
                "concept": "concept1",
                "value": 350.0,
                "unit": "Hz",
                "sample_size": 10,
                "conditions": ["task == 'speech'"],
                "stances": [
                    {
                        "type": "rebuts",
                        "target": "claim1",
                        "strength": "strong",
                        "note": "same task, conflicting value",
                    }
                ],
                "provenance": {"paper": "test_paper_alpha", "page": 8,
                               "date": "2024-06-20"},
            },
            {
                "id": "claim3",
                "type": "parameter",
                "concept": "concept1",
                "value": 180.0,
                "unit": "Hz",
                "conditions": ["task == 'singing'"],
                "provenance": {"paper": "test_paper_alpha", "page": 12},
            },
            {
                "id": "claim4",
                "type": "parameter",
                "concept": "concept2",
                "value": 800.0,
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 15},
            },
            {
                "id": "claim5",
                "type": "observation",
                "statement": "F0 increases with Ps logarithmically.",
                "concepts": ["concept1", "concept2"],
                "provenance": {"paper": "test_paper_alpha", "page": 20},
            },
            {
                "id": "claim10",
                "type": "parameter",
                "concept": "concept6",
                "value": 0.001,
                "unit": "s",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_alpha", "page": 25},
            },
        ],
    }

    beta = {
        "source": {"paper": "test_paper_beta"},
        "claims": [
            {
                "id": "claim6",
                "type": "parameter",
                "concept": "concept2",
                "value": 800.0,
                "unit": "Pa",
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 3},
            },
            {
                "id": "claim7",
                "type": "parameter",
                "concept": "concept1",
                "value": 250.0,
                "unit": "Hz",
                "sample_size": 50,
                "conditions": ["task == 'speech'", "fundamental_frequency > 100"],
                "provenance": {"paper": "test_paper_beta", "page": 7,
                               "date": "2023-03-10"},
                "stances": [
                    {
                        "type": "supports",
                        "target": "claim1",
                        "strength": "moderate",
                        "note": "confirms F0 range",
                    }
                ],
            },
            {
                "id": "claim8",
                "type": "equation",
                "expression": "log(Ps) = 1.00 + 0.88 * log(F0)",
                "sympy": "Eq(log(Ps), 1.00 + 0.88 * log(F0))",
                "variables": [
                    {"symbol": "Ps", "concept": "concept2", "role": "dependent"},
                    {"symbol": "F0", "concept": "concept1", "role": "independent"},
                ],
                "conditions": ["task == 'speech'"],
                "provenance": {"paper": "test_paper_beta", "page": 19},
            },
            {
                "id": "claim9",
                "type": "parameter",
                "concept": "concept1",
                "value": 220.0,
                "unit": "Hz",
                "conditions": ["task == 'whisper'"],
                "provenance": {"paper": "test_paper_beta", "page": 22},
            },
        ],
    }

    (claims_dir / "test_paper_alpha.yaml").write_text(yaml.dump(alpha, default_flow_style=False))
    (claims_dir / "test_paper_beta.yaml").write_text(yaml.dump(beta, default_flow_style=False))

    from propstore.validate_claims import load_claim_files
    return load_claim_files(claims_dir)


@pytest.fixture
def world(concept_dir, repo, claim_files):
    """Build sidecar and return a WorldModel."""
    concepts = load_concepts(concept_dir)
    concept_registry = {c.data["id"]: c.data for c in concepts if c.data.get("id")}
    build_sidecar(concepts, repo.sidecar_path, claim_files=claim_files,
                  concept_registry=concept_registry, repo=repo)
    return WorldModel(repo)


# ── Tests ─────────────────────────────────────────────────────────────


class TestUnboundGraph:
    def test_unbound_graph_has_all_concepts(self, world):
        """All 7 concepts appear as nodes."""
        graph = build_knowledge_graph(world)
        concept_nodes = [n for n in graph.nodes if n.node_type == "concept"]
        concept_ids = {n.id for n in concept_nodes}
        for i in range(1, 8):
            assert f"concept{i}" in concept_ids, f"concept{i} missing from graph"
        assert len(concept_nodes) == 7

    def test_unbound_graph_has_parameterization_edges(self, world):
        """concept6->concept5 and concept1->concept5 parameterization edges exist."""
        graph = build_knowledge_graph(world)
        param_edges = [e for e in graph.edges if e.edge_type == "parameterization"]
        # concept5 has inputs [concept6, concept1]
        param_targets = {(e.source, e.target) for e in param_edges}
        assert ("concept6", "concept5") in param_targets
        assert ("concept1", "concept5") in param_targets

    def test_unbound_graph_has_relationship_edges(self, world):
        """concept1->concept4 broader edge exists."""
        graph = build_knowledge_graph(world)
        rel_edges = [e for e in graph.edges if e.edge_type == "relationship"]
        rel_pairs = {(e.source, e.target) for e in rel_edges}
        assert ("concept1", "concept4") in rel_pairs

    def test_unbound_graph_has_stance_edges(self, world):
        """claim2->claim1 rebuts edge exists."""
        graph = build_knowledge_graph(world)
        stance_edges = [e for e in graph.edges if e.edge_type == "stance"]
        stance_pairs = {(e.source, e.target) for e in stance_edges}
        assert ("claim2", "claim1") in stance_pairs

    def test_measurement_claim_of_edge_uses_target_concept(self, tmp_path):
        sidecar = tmp_path / "propstore.sqlite"
        conn = sqlite3.connect(sidecar)
        conn.executescript("""
            CREATE TABLE concept (
                id TEXT PRIMARY KEY,
                canonical_name TEXT,
                status TEXT,
                domain TEXT,
                form TEXT,
                kind_type TEXT,
                form_parameters TEXT
            );
            CREATE TABLE claim_core (
                id TEXT PRIMARY KEY,
                content_hash TEXT,
                seq INTEGER,
                type TEXT,
                concept_id TEXT,
                target_concept TEXT,
                source_paper TEXT NOT NULL DEFAULT 'test',
                provenance_page INTEGER NOT NULL DEFAULT 1,
                provenance_json TEXT,
                context_id TEXT
            );
            CREATE TABLE claim_numeric_payload (
                claim_id TEXT PRIMARY KEY,
                value REAL,
                lower_bound REAL,
                upper_bound REAL,
                uncertainty REAL,
                uncertainty_type TEXT,
                sample_size INTEGER,
                unit TEXT,
                value_si REAL,
                lower_bound_si REAL,
                upper_bound_si REAL
            );
            CREATE TABLE claim_text_payload (
                claim_id TEXT PRIMARY KEY,
                conditions_cel TEXT,
                statement TEXT,
                expression TEXT,
                sympy_generated TEXT,
                sympy_error TEXT,
                name TEXT,
                measure TEXT,
                listener_population TEXT,
                methodology TEXT,
                notes TEXT,
                description TEXT,
                auto_summary TEXT
            );
            CREATE TABLE claim_algorithm_payload (
                claim_id TEXT PRIMARY KEY,
                body TEXT,
                canonical_ast TEXT,
                variables_json TEXT,
                stage TEXT
            );
        """)
        conn.execute(
            "INSERT INTO concept (id, canonical_name, status, domain, form, kind_type, form_parameters) "
            "VALUES ('concept2', 'jnd_threshold', 'accepted', 'speech', 'frequency', 'quantity', NULL)"
        )
        conn.execute(
            "INSERT INTO claim_core (id, content_hash, seq, type, concept_id, target_concept, source_paper, provenance_page, provenance_json, context_id) "
            "VALUES ('measurement1', 'h1', 1, 'measurement', NULL, 'concept2', 'test', 1, NULL, NULL)"
        )
        conn.execute(
            "INSERT INTO claim_numeric_payload (claim_id, value, lower_bound, upper_bound, uncertainty, uncertainty_type, sample_size, unit, value_si, lower_bound_si, upper_bound_si) "
            "VALUES ('measurement1', 0.14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)"
        )
        conn.execute(
            "INSERT INTO claim_text_payload (claim_id, conditions_cel, statement, expression, sympy_generated, sympy_error, name, measure, listener_population, methodology, notes, description, auto_summary) "
            "VALUES ('measurement1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)"
        )
        conn.execute(
            "INSERT INTO claim_algorithm_payload (claim_id, body, canonical_ast, variables_json, stage) "
            "VALUES ('measurement1', NULL, NULL, NULL, NULL)"
        )
        conn.commit()
        conn.close()

        class _Repo:
            sidecar_path = sidecar

        with WorldModel(_Repo()) as world:
            graph = build_knowledge_graph(world)

        claim_of_edges = [
            edge for edge in graph.edges
            if edge.edge_type == "claim_of" and edge.source == "measurement1"
        ]
        assert len(claim_of_edges) == 1
        assert claim_of_edges[0].target == "concept2"


class TestBoundGraph:
    def test_bound_graph_filters_claims(self, world):
        """Under singing binding, only singing claims appear."""
        bound = world.bind(task="singing")
        graph = build_knowledge_graph(world, bound=bound)
        claim_nodes = [n for n in graph.nodes if n.node_type == "claim"]
        claim_ids = {n.id for n in claim_nodes}
        # claim3 is the singing claim for concept1
        assert "claim3" in claim_ids
        # speech-only claims should not be present
        assert "claim1" not in claim_ids
        assert "claim2" not in claim_ids


class TestGroupScoping:
    def test_group_scoping(self, world):
        """group_id filters to concepts in that group only."""
        # Find which group_id contains concept5
        row = world._conn.execute(
            "SELECT group_id FROM parameterization_group WHERE concept_id = ?",
            ("concept5",),
        ).fetchone()
        assert row is not None, "concept5 should be in a parameterization group"
        gid = row["group_id"]

        graph = build_knowledge_graph(world, group_id=gid)
        concept_nodes = [n for n in graph.nodes if n.node_type == "concept"]
        concept_ids = {n.id for n in concept_nodes}

        # concept5, concept6, concept1, concept7 should be in the group
        # (connected via parameterization)
        assert "concept5" in concept_ids
        # Concepts outside the group should be excluded
        assert "concept3" not in concept_ids


class TestSerialization:
    def test_to_dot_valid(self, world):
        """Output contains 'digraph', node and edge declarations."""
        graph = build_knowledge_graph(world)
        dot = graph.to_dot()
        assert "digraph" in dot
        # Should contain at least one node reference
        assert "concept1" in dot
        # Should contain edge declarations (->)
        assert "->" in dot

    def test_to_json_structure(self, world):
        """Output has nodes/edges keys, each node has id/label/node_type."""
        graph = build_knowledge_graph(world)
        result = graph.to_json()
        assert "nodes" in result
        assert "edges" in result
        assert len(result["nodes"]) > 0
        for node in result["nodes"]:
            assert "id" in node
            assert "label" in node
            assert "node_type" in node
            assert "metadata" in node


class TestConflictedClaims:
    def test_conflicted_claims_marked(self, world):
        """Under speech, concept1 claims marked as conflicted."""
        bound = world.bind(task="speech")
        graph = build_knowledge_graph(world, bound=bound)
        # Find claim nodes for concept1
        concept1_claims = [
            n for n in graph.nodes
            if n.node_type == "claim"
            and n.metadata.get("concept_id") == "concept1"
        ]
        assert len(concept1_claims) > 0
        for claim_node in concept1_claims:
            assert claim_node.metadata.get("status") == "conflicted", (
                f"{claim_node.id} should be marked conflicted under speech"
            )
