"""Propstore world sidecar projection contract."""

from __future__ import annotations

from quire.projections import (
    ProjectionSchema,
    create_projection_schema,
)
from propstore.sidecar.calibration import CALIBRATION_COUNTS_PROJECTION
from propstore.sidecar.claims import (
    CLAIM_ALGORITHM_PAYLOAD_PROJECTION,
    CLAIM_CONCEPT_LINK_PROJECTION,
    CLAIM_CORE_PROJECTION,
    CLAIM_FTS_PROJECTION,
    CLAIM_NUMERIC_PAYLOAD_PROJECTION,
    CLAIM_TEXT_PAYLOAD_PROJECTION,
    CONFLICT_WITNESS_PROJECTION,
    JUSTIFICATION_PROJECTION,
)
from propstore.sidecar.concepts import (
    ALIAS_PROJECTION,
    CONCEPT_FTS_PROJECTION,
    CONCEPT_PROJECTION,
    FORM_ALGEBRA_PROJECTION,
    FORM_PROJECTION,
    PARAMETERIZATION_PROJECTION,
    PARAMETERIZATION_GROUP_PROJECTION,
)
from propstore.sidecar.contexts import (
    CONTEXT_ASSUMPTION_PROJECTION,
    CONTEXT_LIFTING_MATERIALIZATION_PROJECTION,
    CONTEXT_LIFTING_RULE_PROJECTION,
    CONTEXT_PROJECTION,
)
from propstore.sidecar.diagnostics import BUILD_DIAGNOSTICS_PROJECTION
from propstore.sidecar.embedding_store import (
    CONCEPT_EMBEDDING_STATUS_PROJECTION,
    EMBEDDING_MODEL_PROJECTION,
    EMBEDDING_STATUS_PROJECTION,
)
from propstore.sidecar.micropublications import (
    MICROPUBLICATION_CLAIM_PROJECTION,
    MICROPUBLICATION_PROJECTION,
)
from propstore.sidecar.rules import (
    GROUNDED_BUNDLE_INPUT_PROJECTION,
    GROUNDED_FACT_EMPTY_PREDICATE_PROJECTION,
    GROUNDED_FACT_PROJECTION,
)
from propstore.sidecar.relations import RELATION_EDGE_PROJECTION
from propstore.sidecar.sources import SOURCE_PROJECTION


WORLD_SIDECAR_SCHEMA = create_projection_schema(
    SOURCE_PROJECTION,
    CONCEPT_PROJECTION,
    ALIAS_PROJECTION,
    PARAMETERIZATION_PROJECTION,
    PARAMETERIZATION_GROUP_PROJECTION,
    RELATION_EDGE_PROJECTION,
    FORM_PROJECTION,
    FORM_ALGEBRA_PROJECTION,
    CONCEPT_FTS_PROJECTION,
    CONTEXT_PROJECTION,
    CONTEXT_ASSUMPTION_PROJECTION,
    CONTEXT_LIFTING_RULE_PROJECTION,
    CONTEXT_LIFTING_MATERIALIZATION_PROJECTION,
    CLAIM_CORE_PROJECTION,
    CLAIM_CONCEPT_LINK_PROJECTION,
    CLAIM_NUMERIC_PAYLOAD_PROJECTION,
    CLAIM_TEXT_PAYLOAD_PROJECTION,
    CLAIM_ALGORITHM_PAYLOAD_PROJECTION,
    CLAIM_FTS_PROJECTION,
    CONFLICT_WITNESS_PROJECTION,
    GROUNDED_FACT_PROJECTION,
    GROUNDED_FACT_EMPTY_PREDICATE_PROJECTION,
    GROUNDED_BUNDLE_INPUT_PROJECTION,
    JUSTIFICATION_PROJECTION,
    MICROPUBLICATION_PROJECTION,
    MICROPUBLICATION_CLAIM_PROJECTION,
    CALIBRATION_COUNTS_PROJECTION,
    EMBEDDING_MODEL_PROJECTION,
    EMBEDDING_STATUS_PROJECTION,
    CONCEPT_EMBEDDING_STATUS_PROJECTION,
    BUILD_DIAGNOSTICS_PROJECTION,
    metadata={"projection": "propstore.world"},
)
