"""Register missing concepts for the 5-paper claims extraction."""
import subprocess
import sys

concepts = [
    ("assumption_based_tms", "A truth maintenance system that tracks dependencies in terms of underlying assumptions rather than direct justifications"),
    ("environment", "A set of assumptions in an ATMS defining a hypothetical context or world state"),
    ("label", "The set of minimal consistent environments in which a proposition is derivable in an ATMS"),
    ("foundational_belief", "A belief supported by a chain of justifications back to foundational assumptions"),
    ("belief_space", "The set of all propositions derivable from a given context (set of hypotheses)"),
    ("context", "A set of hypotheses that defines a belief space in a multi-context reasoning system"),
    ("current_context", "The context currently under consideration, scoping all retrieval and inference operations"),
    ("origin_set", "The set of hypotheses actually used in deriving a proposition in SWM logic"),
    ("restriction_set", "A set of sets of hypotheses, each known to be inconsistent with a wff's origin set"),
    ("origin_tag", "A tag indicating how a proposition was introduced: hypothesis, derived, or external"),
    ("supported_wff", "A well-formed formula annotated with origin tag, origin set, and restriction set"),
    ("swm_logic", "A relevance logic that tracks propositional dependencies via origin sets and restriction sets"),
    ("snebr", "SNePS Belief Revision system, a concrete implementation of the MBR model using semantic networks"),
    ("culprit_selection", "The process of choosing which hypothesis to retract when a contradiction is detected"),
    ("data_pool", "A hierarchical database context mechanism pairing a bead identifier with a set of assertions"),
    ("data_dependency", "A mechanism tracking reasons for beliefs via justification tuples of in-justifiers and out-justifiers"),
    ("bead", "A unique identifier (natural number) serving as a premiss in a data pool system"),
    ("boolean_label", "A Boolean expression over beads encoding an assertion's status across all data pools simultaneously"),
    ("odd_loop", "A cycle of justifications with an odd number of negative links, which prevents consistent labeling"),
    ("well_founded_labeling", "A status assignment where every IN assertion has grounded support not depending on circular reasoning"),
    ("blocking_bead", "A bead attached to latent assertions that gates their activation when data pool membership changes"),
    ("latent_assertion", "An assertion stored but not indexed, whose label evaluates to OUT in the current data pool"),
    ("signal_function", "A communication mechanism between knowledge-representation and data-dependency levels"),
    ("maxichoice_contraction", "A contraction where the selection function always picks a single element from the remainder set"),
    ("full_meet_contraction", "A contraction where the selection function picks the entire remainder set, yielding the most conservative result"),
    ("transitively_relational", "A property of selection functions that can be generated by a transitive ordering over remainder set elements"),
]

for name, definition in concepts:
    cmd = [
        "uv", "run", "pks", "concept", "add",
        "--domain", "argumentation",
        "--name", name,
        "--form", "structural",
        "--definition", definition,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"FAIL: {name}: {result.stderr.strip()}", file=sys.stderr)
    else:
        print(result.stdout.strip())
