"""Family-owned derived projection catalog."""

from __future__ import annotations

from quire.projections import ProjectionSchema, create_projection_schema

from propstore.families.calibration.declaration import CALIBRATION_COUNTS_PROJECTION
from propstore.families.claims.declaration import (
    CLAIM_ALGORITHM_PAYLOAD_TABLE,
    CLAIM_CONCEPT_LINK_TABLE,
    CLAIM_CORE_TABLE,
    CLAIM_EMBEDDING_STATUS_PROJECTION,
    CLAIM_FTS_PROJECTION,
    CLAIM_NUMERIC_PAYLOAD_TABLE,
    CLAIM_TEXT_PAYLOAD_TABLE,
    CONFLICT_WITNESS_TABLE,
    JUSTIFICATION_TABLE,
)
from propstore.families.concepts.declaration import (
    ALIAS_PROJECTION,
    CONCEPT_EMBEDDING_STATUS_PROJECTION,
    CONCEPT_FTS_PROJECTION,
    CONCEPT_PROJECTION,
    FORM_ALGEBRA_PROJECTION,
    FORM_PROJECTION,
    PARAMETERIZATION_GROUP_PROJECTION,
    PARAMETERIZATION_PROJECTION,
    RELATIONSHIP_PROJECTION,
)
from propstore.families.contexts.declaration import (
    CONTEXT_ASSUMPTION_TABLE,
    CONTEXT_LIFTING_MATERIALIZATION_TABLE,
    CONTEXT_LIFTING_RULE_TABLE,
    CONTEXT_TABLE,
)
from propstore.families.diagnostics.declaration import BUILD_DIAGNOSTICS_PROJECTION
from propstore.families.embeddings.declaration import EMBEDDING_MODEL_PROJECTION
from propstore.families.micropublications.declaration import (
    MICROPUBLICATION_CLAIM_PROJECTION,
    MICROPUBLICATION_PROJECTION,
)
from propstore.families.relations.declaration import RELATION_EDGE_TABLE
from propstore.families.rules.declaration import (
    GROUNDED_BUNDLE_INPUT_PROJECTION,
    GROUNDED_FACT_EMPTY_PREDICATE_PROJECTION,
    GROUNDED_FACT_PROJECTION,
)
from propstore.families.sources.declaration import SOURCE_PROJECTION

PROPSTORE_WORLD_SCHEMA_VERSION = 6
PROPSTORE_WORLD_META_KEY = "sidecar"

PROPSTORE_WORLD_PROJECTION_SCHEMA: ProjectionSchema = create_projection_schema(
    SOURCE_PROJECTION,
    CONCEPT_PROJECTION,
    ALIAS_PROJECTION,
    PARAMETERIZATION_PROJECTION,
    PARAMETERIZATION_GROUP_PROJECTION,
    RELATIONSHIP_PROJECTION,
    RELATION_EDGE_TABLE,
    FORM_PROJECTION,
    FORM_ALGEBRA_PROJECTION,
    CONCEPT_FTS_PROJECTION,
    CONTEXT_TABLE,
    CONTEXT_ASSUMPTION_TABLE,
    CONTEXT_LIFTING_RULE_TABLE,
    CONTEXT_LIFTING_MATERIALIZATION_TABLE,
    CLAIM_CORE_TABLE,
    CLAIM_CONCEPT_LINK_TABLE,
    CLAIM_NUMERIC_PAYLOAD_TABLE,
    CLAIM_TEXT_PAYLOAD_TABLE,
    CLAIM_ALGORITHM_PAYLOAD_TABLE,
    CLAIM_FTS_PROJECTION,
    CONFLICT_WITNESS_TABLE,
    GROUNDED_FACT_PROJECTION,
    GROUNDED_FACT_EMPTY_PREDICATE_PROJECTION,
    GROUNDED_BUNDLE_INPUT_PROJECTION,
    JUSTIFICATION_TABLE,
    MICROPUBLICATION_PROJECTION,
    MICROPUBLICATION_CLAIM_PROJECTION,
    CALIBRATION_COUNTS_PROJECTION,
    EMBEDDING_MODEL_PROJECTION,
    CLAIM_EMBEDDING_STATUS_PROJECTION,
    CONCEPT_EMBEDDING_STATUS_PROJECTION,
    BUILD_DIAGNOSTICS_PROJECTION,
    metadata={"projection": "propstore.world"},
)
